/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FinancialStatements
 */
@JsonPropertyOrder({
  FinancialStatements.JSON_PROPERTY_SYMBOL,
  FinancialStatements.JSON_PROPERTY_FINANCIALS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class FinancialStatements {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_FINANCIALS = "financials";
  @javax.annotation.Nullable
  private List<Object> financials = new ArrayList<>();

  public FinancialStatements() {
  }

  public FinancialStatements symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Symbol of the company.
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public FinancialStatements financials(@javax.annotation.Nullable List<Object> financials) {
    
    this.financials = financials;
    return this;
  }

  public FinancialStatements addFinancialsItem(Object financialsItem) {
    if (this.financials == null) {
      this.financials = new ArrayList<>();
    }
    this.financials.add(financialsItem);
    return this;
  }

  /**
   * An array of map of key, value pairs containing the data for each period.
   * @return financials
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINANCIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getFinancials() {
    return financials;
  }


  @JsonProperty(JSON_PROPERTY_FINANCIALS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinancials(@javax.annotation.Nullable List<Object> financials) {
    this.financials = financials;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialStatements financialStatements = (FinancialStatements) o;
    return Objects.equals(this.symbol, financialStatements.symbol) &&
        Objects.equals(this.financials, financialStatements.financials);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, financials);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialStatements {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    financials: ").append(toIndentedString(financials)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

