/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MarketNews
 */
@JsonPropertyOrder({
  MarketNews.JSON_PROPERTY_CATEGORY,
  MarketNews.JSON_PROPERTY_DATETIME,
  MarketNews.JSON_PROPERTY_HEADLINE,
  MarketNews.JSON_PROPERTY_ID,
  MarketNews.JSON_PROPERTY_IMAGE,
  MarketNews.JSON_PROPERTY_RELATED,
  MarketNews.JSON_PROPERTY_SOURCE,
  MarketNews.JSON_PROPERTY_SUMMARY,
  MarketNews.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MarketNews {
  public static final String JSON_PROPERTY_CATEGORY = "category";
  @javax.annotation.Nullable
  private String category;

  public static final String JSON_PROPERTY_DATETIME = "datetime";
  @javax.annotation.Nullable
  private Long datetime;

  public static final String JSON_PROPERTY_HEADLINE = "headline";
  @javax.annotation.Nullable
  private String headline;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_IMAGE = "image";
  @javax.annotation.Nullable
  private String image;

  public static final String JSON_PROPERTY_RELATED = "related";
  @javax.annotation.Nullable
  private String related;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @javax.annotation.Nullable
  private String source;

  public static final String JSON_PROPERTY_SUMMARY = "summary";
  @javax.annotation.Nullable
  private String summary;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public MarketNews() {
  }

  public MarketNews category(@javax.annotation.Nullable String category) {
    
    this.category = category;
    return this;
  }

  /**
   * News category.
   * @return category
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCategory() {
    return category;
  }


  @JsonProperty(JSON_PROPERTY_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategory(@javax.annotation.Nullable String category) {
    this.category = category;
  }

  public MarketNews datetime(@javax.annotation.Nullable Long datetime) {
    
    this.datetime = datetime;
    return this;
  }

  /**
   * Published time in UNIX timestamp.
   * @return datetime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDatetime() {
    return datetime;
  }


  @JsonProperty(JSON_PROPERTY_DATETIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatetime(@javax.annotation.Nullable Long datetime) {
    this.datetime = datetime;
  }

  public MarketNews headline(@javax.annotation.Nullable String headline) {
    
    this.headline = headline;
    return this;
  }

  /**
   * News headline.
   * @return headline
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HEADLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHeadline() {
    return headline;
  }


  @JsonProperty(JSON_PROPERTY_HEADLINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHeadline(@javax.annotation.Nullable String headline) {
    this.headline = headline;
  }

  public MarketNews id(@javax.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * News ID. This value can be used for &lt;code&gt;minId&lt;/code&gt; params to get the latest news only.
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }

  public MarketNews image(@javax.annotation.Nullable String image) {
    
    this.image = image;
    return this;
  }

  /**
   * Thumbnail image URL.
   * @return image
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImage() {
    return image;
  }


  @JsonProperty(JSON_PROPERTY_IMAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImage(@javax.annotation.Nullable String image) {
    this.image = image;
  }

  public MarketNews related(@javax.annotation.Nullable String related) {
    
    this.related = related;
    return this;
  }

  /**
   * Related stocks and companies mentioned in the article.
   * @return related
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRelated() {
    return related;
  }


  @JsonProperty(JSON_PROPERTY_RELATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelated(@javax.annotation.Nullable String related) {
    this.related = related;
  }

  public MarketNews source(@javax.annotation.Nullable String source) {
    
    this.source = source;
    return this;
  }

  /**
   * News source.
   * @return source
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@javax.annotation.Nullable String source) {
    this.source = source;
  }

  public MarketNews summary(@javax.annotation.Nullable String summary) {
    
    this.summary = summary;
    return this;
  }

  /**
   * News summary.
   * @return summary
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSummary() {
    return summary;
  }


  @JsonProperty(JSON_PROPERTY_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSummary(@javax.annotation.Nullable String summary) {
    this.summary = summary;
  }

  public MarketNews url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * URL of the original article.
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketNews marketNews = (MarketNews) o;
    return Objects.equals(this.category, marketNews.category) &&
        Objects.equals(this.datetime, marketNews.datetime) &&
        Objects.equals(this.headline, marketNews.headline) &&
        Objects.equals(this.id, marketNews.id) &&
        Objects.equals(this.image, marketNews.image) &&
        Objects.equals(this.related, marketNews.related) &&
        Objects.equals(this.source, marketNews.source) &&
        Objects.equals(this.summary, marketNews.summary) &&
        Objects.equals(this.url, marketNews.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, datetime, headline, id, image, related, source, summary, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketNews {\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    headline: ").append(toIndentedString(headline)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    related: ").append(toIndentedString(related)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    summary: ").append(toIndentedString(summary)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

