/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Trend
 */
@JsonPropertyOrder({
  Trend.JSON_PROPERTY_ADX,
  Trend.JSON_PROPERTY_TRENDING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class Trend {
  public static final String JSON_PROPERTY_ADX = "adx";
  @javax.annotation.Nullable
  private Float adx;

  public static final String JSON_PROPERTY_TRENDING = "trending";
  @javax.annotation.Nullable
  private Boolean trending;

  public Trend() {
  }

  public Trend adx(@javax.annotation.Nullable Float adx) {
    
    this.adx = adx;
    return this;
  }

  /**
   * ADX reading
   * @return adx
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAdx() {
    return adx;
  }


  @JsonProperty(JSON_PROPERTY_ADX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdx(@javax.annotation.Nullable Float adx) {
    this.adx = adx;
  }

  public Trend trending(@javax.annotation.Nullable Boolean trending) {
    
    this.trending = trending;
    return this;
  }

  /**
   * Whether market is trending or going sideway
   * @return trending
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRENDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrending() {
    return trending;
  }


  @JsonProperty(JSON_PROPERTY_TRENDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrending(@javax.annotation.Nullable Boolean trending) {
    this.trending = trending;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Trend trend = (Trend) o;
    return Objects.equals(this.adx, trend.adx) &&
        Objects.equals(this.trending, trend.trending);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adx, trending);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Trend {\n");
    sb.append("    adx: ").append(toIndentedString(adx)).append("\n");
    sb.append("    trending: ").append(toIndentedString(trending)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

