/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * BankBranchData
 */
@JsonPropertyOrder({
  BankBranchData.JSON_PROPERTY_BRANCH_ID,
  BankBranchData.JSON_PROPERTY_ADDRESS,
  BankBranchData.JSON_PROPERTY_STATE,
  BankBranchData.JSON_PROPERTY_ZIP_CODE,
  BankBranchData.JSON_PROPERTY_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class BankBranchData {
  public static final String JSON_PROPERTY_BRANCH_ID = "branchId";
  @javax.annotation.Nullable
  private String branchId;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_ZIP_CODE = "zipCode";
  @javax.annotation.Nullable
  private String zipCode;

  public static final String JSON_PROPERTY_DATE = "date";
  @javax.annotation.Nullable
  private String date;

  public BankBranchData() {
  }

  public BankBranchData branchId(@javax.annotation.Nullable String branchId) {
    
    this.branchId = branchId;
    return this;
  }

  /**
   * Branch ID
   * @return branchId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BRANCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBranchId() {
    return branchId;
  }


  @JsonProperty(JSON_PROPERTY_BRANCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranchId(@javax.annotation.Nullable String branchId) {
    this.branchId = branchId;
  }

  public BankBranchData address(@javax.annotation.Nullable String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Branch address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }

  public BankBranchData state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * State
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }

  public BankBranchData zipCode(@javax.annotation.Nullable String zipCode) {
    
    this.zipCode = zipCode;
    return this;
  }

  /**
   *  Zip code
   * @return zipCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getZipCode() {
    return zipCode;
  }


  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZipCode(@javax.annotation.Nullable String zipCode) {
    this.zipCode = zipCode;
  }

  public BankBranchData date(@javax.annotation.Nullable String date) {
    
    this.date = date;
    return this;
  }

  /**
   * Date opened
   * @return date
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(@javax.annotation.Nullable String date) {
    this.date = date;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankBranchData bankBranchData = (BankBranchData) o;
    return Objects.equals(this.branchId, bankBranchData.branchId) &&
        Objects.equals(this.address, bankBranchData.address) &&
        Objects.equals(this.state, bankBranchData.state) &&
        Objects.equals(this.zipCode, bankBranchData.zipCode) &&
        Objects.equals(this.date, bankBranchData.date);
  }

  @Override
  public int hashCode() {
    return Objects.hash(branchId, address, state, zipCode, date);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankBranchData {\n");
    sb.append("    branchId: ").append(toIndentedString(branchId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

