/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CompanyProfile2
 */
@JsonPropertyOrder({
  CompanyProfile2.JSON_PROPERTY_COUNTRY,
  CompanyProfile2.JSON_PROPERTY_CURRENCY,
  CompanyProfile2.JSON_PROPERTY_EXCHANGE,
  CompanyProfile2.JSON_PROPERTY_NAME,
  CompanyProfile2.JSON_PROPERTY_TICKER,
  CompanyProfile2.JSON_PROPERTY_IPO,
  CompanyProfile2.JSON_PROPERTY_MARKET_CAPITALIZATION,
  CompanyProfile2.JSON_PROPERTY_SHARE_OUTSTANDING,
  CompanyProfile2.JSON_PROPERTY_LOGO,
  CompanyProfile2.JSON_PROPERTY_PHONE,
  CompanyProfile2.JSON_PROPERTY_WEBURL,
  CompanyProfile2.JSON_PROPERTY_FINNHUB_INDUSTRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CompanyProfile2 {
  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_TICKER = "ticker";
  @javax.annotation.Nullable
  private String ticker;

  public static final String JSON_PROPERTY_IPO = "ipo";
  @javax.annotation.Nullable
  private LocalDate ipo;

  public static final String JSON_PROPERTY_MARKET_CAPITALIZATION = "marketCapitalization";
  @javax.annotation.Nullable
  private Float marketCapitalization;

  public static final String JSON_PROPERTY_SHARE_OUTSTANDING = "shareOutstanding";
  @javax.annotation.Nullable
  private Float shareOutstanding;

  public static final String JSON_PROPERTY_LOGO = "logo";
  @javax.annotation.Nullable
  private String logo;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_WEBURL = "weburl";
  @javax.annotation.Nullable
  private String weburl;

  public static final String JSON_PROPERTY_FINNHUB_INDUSTRY = "finnhubIndustry";
  @javax.annotation.Nullable
  private String finnhubIndustry;

  public CompanyProfile2() {
  }

  public CompanyProfile2 country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Country of company&#39;s headquarter.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public CompanyProfile2 currency(@javax.annotation.Nullable String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Currency used in company filings.
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }

  public CompanyProfile2 exchange(@javax.annotation.Nullable String exchange) {
    
    this.exchange = exchange;
    return this;
  }

  /**
   * Listed exchange.
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchange() {
    return exchange;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }

  public CompanyProfile2 name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Company name.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public CompanyProfile2 ticker(@javax.annotation.Nullable String ticker) {
    
    this.ticker = ticker;
    return this;
  }

  /**
   * Company symbol/ticker as used on the listed exchange.
   * @return ticker
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TICKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicker() {
    return ticker;
  }


  @JsonProperty(JSON_PROPERTY_TICKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicker(@javax.annotation.Nullable String ticker) {
    this.ticker = ticker;
  }

  public CompanyProfile2 ipo(@javax.annotation.Nullable LocalDate ipo) {
    
    this.ipo = ipo;
    return this;
  }

  /**
   * IPO date.
   * @return ipo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IPO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getIpo() {
    return ipo;
  }


  @JsonProperty(JSON_PROPERTY_IPO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpo(@javax.annotation.Nullable LocalDate ipo) {
    this.ipo = ipo;
  }

  public CompanyProfile2 marketCapitalization(@javax.annotation.Nullable Float marketCapitalization) {
    
    this.marketCapitalization = marketCapitalization;
    return this;
  }

  /**
   * Market Capitalization.
   * @return marketCapitalization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKET_CAPITALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMarketCapitalization() {
    return marketCapitalization;
  }


  @JsonProperty(JSON_PROPERTY_MARKET_CAPITALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapitalization(@javax.annotation.Nullable Float marketCapitalization) {
    this.marketCapitalization = marketCapitalization;
  }

  public CompanyProfile2 shareOutstanding(@javax.annotation.Nullable Float shareOutstanding) {
    
    this.shareOutstanding = shareOutstanding;
    return this;
  }

  /**
   * Number of oustanding shares.
   * @return shareOutstanding
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARE_OUTSTANDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getShareOutstanding() {
    return shareOutstanding;
  }


  @JsonProperty(JSON_PROPERTY_SHARE_OUTSTANDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShareOutstanding(@javax.annotation.Nullable Float shareOutstanding) {
    this.shareOutstanding = shareOutstanding;
  }

  public CompanyProfile2 logo(@javax.annotation.Nullable String logo) {
    
    this.logo = logo;
    return this;
  }

  /**
   * Logo image.
   * @return logo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogo() {
    return logo;
  }


  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogo(@javax.annotation.Nullable String logo) {
    this.logo = logo;
  }

  public CompanyProfile2 phone(@javax.annotation.Nullable String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Company phone number.
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }

  public CompanyProfile2 weburl(@javax.annotation.Nullable String weburl) {
    
    this.weburl = weburl;
    return this;
  }

  /**
   * Company website.
   * @return weburl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWeburl() {
    return weburl;
  }


  @JsonProperty(JSON_PROPERTY_WEBURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeburl(@javax.annotation.Nullable String weburl) {
    this.weburl = weburl;
  }

  public CompanyProfile2 finnhubIndustry(@javax.annotation.Nullable String finnhubIndustry) {
    
    this.finnhubIndustry = finnhubIndustry;
    return this;
  }

  /**
   * Finnhub industry classification.
   * @return finnhubIndustry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINNHUB_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFinnhubIndustry() {
    return finnhubIndustry;
  }


  @JsonProperty(JSON_PROPERTY_FINNHUB_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinnhubIndustry(@javax.annotation.Nullable String finnhubIndustry) {
    this.finnhubIndustry = finnhubIndustry;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyProfile2 companyProfile2 = (CompanyProfile2) o;
    return Objects.equals(this.country, companyProfile2.country) &&
        Objects.equals(this.currency, companyProfile2.currency) &&
        Objects.equals(this.exchange, companyProfile2.exchange) &&
        Objects.equals(this.name, companyProfile2.name) &&
        Objects.equals(this.ticker, companyProfile2.ticker) &&
        Objects.equals(this.ipo, companyProfile2.ipo) &&
        Objects.equals(this.marketCapitalization, companyProfile2.marketCapitalization) &&
        Objects.equals(this.shareOutstanding, companyProfile2.shareOutstanding) &&
        Objects.equals(this.logo, companyProfile2.logo) &&
        Objects.equals(this.phone, companyProfile2.phone) &&
        Objects.equals(this.weburl, companyProfile2.weburl) &&
        Objects.equals(this.finnhubIndustry, companyProfile2.finnhubIndustry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, currency, exchange, name, ticker, ipo, marketCapitalization, shareOutstanding, logo, phone, weburl, finnhubIndustry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyProfile2 {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    ipo: ").append(toIndentedString(ipo)).append("\n");
    sb.append("    marketCapitalization: ").append(toIndentedString(marketCapitalization)).append("\n");
    sb.append("    shareOutstanding: ").append(toIndentedString(shareOutstanding)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    weburl: ").append(toIndentedString(weburl)).append("\n");
    sb.append("    finnhubIndustry: ").append(toIndentedString(finnhubIndustry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

