/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CompanyProfile
 */
@JsonPropertyOrder({
  CompanyProfile.JSON_PROPERTY_ALIAS,
  CompanyProfile.JSON_PROPERTY_ADDRESS,
  CompanyProfile.JSON_PROPERTY_CITY,
  CompanyProfile.JSON_PROPERTY_COUNTRY,
  CompanyProfile.JSON_PROPERTY_CURRENCY,
  CompanyProfile.JSON_PROPERTY_ESTIMATE_CURRENCY,
  CompanyProfile.JSON_PROPERTY_MARKET_CAP_CURRENCY,
  CompanyProfile.JSON_PROPERTY_CUSIP,
  CompanyProfile.JSON_PROPERTY_SEDOL,
  CompanyProfile.JSON_PROPERTY_DESCRIPTION,
  CompanyProfile.JSON_PROPERTY_EXCHANGE,
  CompanyProfile.JSON_PROPERTY_GGROUP,
  CompanyProfile.JSON_PROPERTY_GIND,
  CompanyProfile.JSON_PROPERTY_GSECTOR,
  CompanyProfile.JSON_PROPERTY_GSUBIND,
  CompanyProfile.JSON_PROPERTY_ISIN,
  CompanyProfile.JSON_PROPERTY_LEI,
  CompanyProfile.JSON_PROPERTY_IR_URL,
  CompanyProfile.JSON_PROPERTY_NAICS_NATIONAL_INDUSTRY,
  CompanyProfile.JSON_PROPERTY_NAICS,
  CompanyProfile.JSON_PROPERTY_NAICS_SECTOR,
  CompanyProfile.JSON_PROPERTY_NAICS_SUBSECTOR,
  CompanyProfile.JSON_PROPERTY_NAME,
  CompanyProfile.JSON_PROPERTY_PHONE,
  CompanyProfile.JSON_PROPERTY_STATE,
  CompanyProfile.JSON_PROPERTY_TICKER,
  CompanyProfile.JSON_PROPERTY_WEBURL,
  CompanyProfile.JSON_PROPERTY_IPO,
  CompanyProfile.JSON_PROPERTY_MARKET_CAPITALIZATION,
  CompanyProfile.JSON_PROPERTY_SHARE_OUTSTANDING,
  CompanyProfile.JSON_PROPERTY_EMPLOYEE_TOTAL,
  CompanyProfile.JSON_PROPERTY_LOGO,
  CompanyProfile.JSON_PROPERTY_FINNHUB_INDUSTRY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CompanyProfile {
  public static final String JSON_PROPERTY_ALIAS = "alias";
  @javax.annotation.Nullable
  private List<String> alias = new ArrayList<>();

  public static final String JSON_PROPERTY_ADDRESS = "address";
  @javax.annotation.Nullable
  private String address;

  public static final String JSON_PROPERTY_CITY = "city";
  @javax.annotation.Nullable
  private String city;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_ESTIMATE_CURRENCY = "estimateCurrency";
  @javax.annotation.Nullable
  private String estimateCurrency;

  public static final String JSON_PROPERTY_MARKET_CAP_CURRENCY = "marketCapCurrency";
  @javax.annotation.Nullable
  private String marketCapCurrency;

  public static final String JSON_PROPERTY_CUSIP = "cusip";
  @javax.annotation.Nullable
  private String cusip;

  public static final String JSON_PROPERTY_SEDOL = "sedol";
  @javax.annotation.Nullable
  private String sedol;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_EXCHANGE = "exchange";
  @javax.annotation.Nullable
  private String exchange;

  public static final String JSON_PROPERTY_GGROUP = "ggroup";
  @javax.annotation.Nullable
  private String ggroup;

  public static final String JSON_PROPERTY_GIND = "gind";
  @javax.annotation.Nullable
  private String gind;

  public static final String JSON_PROPERTY_GSECTOR = "gsector";
  @javax.annotation.Nullable
  private String gsector;

  public static final String JSON_PROPERTY_GSUBIND = "gsubind";
  @javax.annotation.Nullable
  private String gsubind;

  public static final String JSON_PROPERTY_ISIN = "isin";
  @javax.annotation.Nullable
  private String isin;

  public static final String JSON_PROPERTY_LEI = "lei";
  @javax.annotation.Nullable
  private String lei;

  public static final String JSON_PROPERTY_IR_URL = "irUrl";
  @javax.annotation.Nullable
  private String irUrl;

  public static final String JSON_PROPERTY_NAICS_NATIONAL_INDUSTRY = "naicsNationalIndustry";
  @javax.annotation.Nullable
  private String naicsNationalIndustry;

  public static final String JSON_PROPERTY_NAICS = "naics";
  @javax.annotation.Nullable
  private String naics;

  public static final String JSON_PROPERTY_NAICS_SECTOR = "naicsSector";
  @javax.annotation.Nullable
  private String naicsSector;

  public static final String JSON_PROPERTY_NAICS_SUBSECTOR = "naicsSubsector";
  @javax.annotation.Nullable
  private String naicsSubsector;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PHONE = "phone";
  @javax.annotation.Nullable
  private String phone;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private String state;

  public static final String JSON_PROPERTY_TICKER = "ticker";
  @javax.annotation.Nullable
  private String ticker;

  public static final String JSON_PROPERTY_WEBURL = "weburl";
  @javax.annotation.Nullable
  private String weburl;

  public static final String JSON_PROPERTY_IPO = "ipo";
  @javax.annotation.Nullable
  private LocalDate ipo;

  public static final String JSON_PROPERTY_MARKET_CAPITALIZATION = "marketCapitalization";
  @javax.annotation.Nullable
  private Float marketCapitalization;

  public static final String JSON_PROPERTY_SHARE_OUTSTANDING = "shareOutstanding";
  @javax.annotation.Nullable
  private Float shareOutstanding;

  public static final String JSON_PROPERTY_EMPLOYEE_TOTAL = "employeeTotal";
  @javax.annotation.Nullable
  private Float employeeTotal;

  public static final String JSON_PROPERTY_LOGO = "logo";
  @javax.annotation.Nullable
  private String logo;

  public static final String JSON_PROPERTY_FINNHUB_INDUSTRY = "finnhubIndustry";
  @javax.annotation.Nullable
  private String finnhubIndustry;

  public CompanyProfile() {
  }

  public CompanyProfile alias(@javax.annotation.Nullable List<String> alias) {
    
    this.alias = alias;
    return this;
  }

  public CompanyProfile addAliasItem(String aliasItem) {
    if (this.alias == null) {
      this.alias = new ArrayList<>();
    }
    this.alias.add(aliasItem);
    return this;
  }

  /**
   * Company name alias.
   * @return alias
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAlias() {
    return alias;
  }


  @JsonProperty(JSON_PROPERTY_ALIAS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlias(@javax.annotation.Nullable List<String> alias) {
    this.alias = alias;
  }

  public CompanyProfile address(@javax.annotation.Nullable String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Address of company&#39;s headquarter.
   * @return address
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = address;
  }

  public CompanyProfile city(@javax.annotation.Nullable String city) {
    
    this.city = city;
    return this;
  }

  /**
   * City of company&#39;s headquarter.
   * @return city
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(@javax.annotation.Nullable String city) {
    this.city = city;
  }

  public CompanyProfile country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Country of company&#39;s headquarter.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public CompanyProfile currency(@javax.annotation.Nullable String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Currency used in company filings and financials.
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }

  public CompanyProfile estimateCurrency(@javax.annotation.Nullable String estimateCurrency) {
    
    this.estimateCurrency = estimateCurrency;
    return this;
  }

  /**
   * Currency used in Estimates data.
   * @return estimateCurrency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ESTIMATE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEstimateCurrency() {
    return estimateCurrency;
  }


  @JsonProperty(JSON_PROPERTY_ESTIMATE_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEstimateCurrency(@javax.annotation.Nullable String estimateCurrency) {
    this.estimateCurrency = estimateCurrency;
  }

  public CompanyProfile marketCapCurrency(@javax.annotation.Nullable String marketCapCurrency) {
    
    this.marketCapCurrency = marketCapCurrency;
    return this;
  }

  /**
   * Currency used in market capitalization.
   * @return marketCapCurrency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKET_CAP_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMarketCapCurrency() {
    return marketCapCurrency;
  }


  @JsonProperty(JSON_PROPERTY_MARKET_CAP_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapCurrency(@javax.annotation.Nullable String marketCapCurrency) {
    this.marketCapCurrency = marketCapCurrency;
  }

  public CompanyProfile cusip(@javax.annotation.Nullable String cusip) {
    
    this.cusip = cusip;
    return this;
  }

  /**
   * CUSIP number.
   * @return cusip
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCusip() {
    return cusip;
  }


  @JsonProperty(JSON_PROPERTY_CUSIP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCusip(@javax.annotation.Nullable String cusip) {
    this.cusip = cusip;
  }

  public CompanyProfile sedol(@javax.annotation.Nullable String sedol) {
    
    this.sedol = sedol;
    return this;
  }

  /**
   * Sedol number.
   * @return sedol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEDOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSedol() {
    return sedol;
  }


  @JsonProperty(JSON_PROPERTY_SEDOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSedol(@javax.annotation.Nullable String sedol) {
    this.sedol = sedol;
  }

  public CompanyProfile description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Company business summary.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public CompanyProfile exchange(@javax.annotation.Nullable String exchange) {
    
    this.exchange = exchange;
    return this;
  }

  /**
   * Listed exchange.
   * @return exchange
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchange() {
    return exchange;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchange(@javax.annotation.Nullable String exchange) {
    this.exchange = exchange;
  }

  public CompanyProfile ggroup(@javax.annotation.Nullable String ggroup) {
    
    this.ggroup = ggroup;
    return this;
  }

  /**
   * Industry group.
   * @return ggroup
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GGROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGgroup() {
    return ggroup;
  }


  @JsonProperty(JSON_PROPERTY_GGROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGgroup(@javax.annotation.Nullable String ggroup) {
    this.ggroup = ggroup;
  }

  public CompanyProfile gind(@javax.annotation.Nullable String gind) {
    
    this.gind = gind;
    return this;
  }

  /**
   * Industry.
   * @return gind
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGind() {
    return gind;
  }


  @JsonProperty(JSON_PROPERTY_GIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGind(@javax.annotation.Nullable String gind) {
    this.gind = gind;
  }

  public CompanyProfile gsector(@javax.annotation.Nullable String gsector) {
    
    this.gsector = gsector;
    return this;
  }

  /**
   * Sector.
   * @return gsector
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GSECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGsector() {
    return gsector;
  }


  @JsonProperty(JSON_PROPERTY_GSECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGsector(@javax.annotation.Nullable String gsector) {
    this.gsector = gsector;
  }

  public CompanyProfile gsubind(@javax.annotation.Nullable String gsubind) {
    
    this.gsubind = gsubind;
    return this;
  }

  /**
   * Sub-industry.
   * @return gsubind
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GSUBIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGsubind() {
    return gsubind;
  }


  @JsonProperty(JSON_PROPERTY_GSUBIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGsubind(@javax.annotation.Nullable String gsubind) {
    this.gsubind = gsubind;
  }

  public CompanyProfile isin(@javax.annotation.Nullable String isin) {
    
    this.isin = isin;
    return this;
  }

  /**
   * ISIN number.
   * @return isin
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIsin() {
    return isin;
  }


  @JsonProperty(JSON_PROPERTY_ISIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsin(@javax.annotation.Nullable String isin) {
    this.isin = isin;
  }

  public CompanyProfile lei(@javax.annotation.Nullable String lei) {
    
    this.lei = lei;
    return this;
  }

  /**
   * LEI number.
   * @return lei
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LEI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLei() {
    return lei;
  }


  @JsonProperty(JSON_PROPERTY_LEI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLei(@javax.annotation.Nullable String lei) {
    this.lei = lei;
  }

  public CompanyProfile irUrl(@javax.annotation.Nullable String irUrl) {
    
    this.irUrl = irUrl;
    return this;
  }

  /**
   * Investor relations website.
   * @return irUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIrUrl() {
    return irUrl;
  }


  @JsonProperty(JSON_PROPERTY_IR_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIrUrl(@javax.annotation.Nullable String irUrl) {
    this.irUrl = irUrl;
  }

  public CompanyProfile naicsNationalIndustry(@javax.annotation.Nullable String naicsNationalIndustry) {
    
    this.naicsNationalIndustry = naicsNationalIndustry;
    return this;
  }

  /**
   * NAICS national industry.
   * @return naicsNationalIndustry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAICS_NATIONAL_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNaicsNationalIndustry() {
    return naicsNationalIndustry;
  }


  @JsonProperty(JSON_PROPERTY_NAICS_NATIONAL_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNaicsNationalIndustry(@javax.annotation.Nullable String naicsNationalIndustry) {
    this.naicsNationalIndustry = naicsNationalIndustry;
  }

  public CompanyProfile naics(@javax.annotation.Nullable String naics) {
    
    this.naics = naics;
    return this;
  }

  /**
   * NAICS industry.
   * @return naics
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNaics() {
    return naics;
  }


  @JsonProperty(JSON_PROPERTY_NAICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNaics(@javax.annotation.Nullable String naics) {
    this.naics = naics;
  }

  public CompanyProfile naicsSector(@javax.annotation.Nullable String naicsSector) {
    
    this.naicsSector = naicsSector;
    return this;
  }

  /**
   * NAICS sector.
   * @return naicsSector
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAICS_SECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNaicsSector() {
    return naicsSector;
  }


  @JsonProperty(JSON_PROPERTY_NAICS_SECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNaicsSector(@javax.annotation.Nullable String naicsSector) {
    this.naicsSector = naicsSector;
  }

  public CompanyProfile naicsSubsector(@javax.annotation.Nullable String naicsSubsector) {
    
    this.naicsSubsector = naicsSubsector;
    return this;
  }

  /**
   * NAICS subsector.
   * @return naicsSubsector
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAICS_SUBSECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNaicsSubsector() {
    return naicsSubsector;
  }


  @JsonProperty(JSON_PROPERTY_NAICS_SUBSECTOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNaicsSubsector(@javax.annotation.Nullable String naicsSubsector) {
    this.naicsSubsector = naicsSubsector;
  }

  public CompanyProfile name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Company name.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public CompanyProfile phone(@javax.annotation.Nullable String phone) {
    
    this.phone = phone;
    return this;
  }

  /**
   * Company phone number.
   * @return phone
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhone() {
    return phone;
  }


  @JsonProperty(JSON_PROPERTY_PHONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhone(@javax.annotation.Nullable String phone) {
    this.phone = phone;
  }

  public CompanyProfile state(@javax.annotation.Nullable String state) {
    
    this.state = state;
    return this;
  }

  /**
   * State of company&#39;s headquarter.
   * @return state
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@javax.annotation.Nullable String state) {
    this.state = state;
  }

  public CompanyProfile ticker(@javax.annotation.Nullable String ticker) {
    
    this.ticker = ticker;
    return this;
  }

  /**
   * Company symbol/ticker as used on the listed exchange.
   * @return ticker
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TICKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTicker() {
    return ticker;
  }


  @JsonProperty(JSON_PROPERTY_TICKER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTicker(@javax.annotation.Nullable String ticker) {
    this.ticker = ticker;
  }

  public CompanyProfile weburl(@javax.annotation.Nullable String weburl) {
    
    this.weburl = weburl;
    return this;
  }

  /**
   * Company website.
   * @return weburl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEBURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getWeburl() {
    return weburl;
  }


  @JsonProperty(JSON_PROPERTY_WEBURL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeburl(@javax.annotation.Nullable String weburl) {
    this.weburl = weburl;
  }

  public CompanyProfile ipo(@javax.annotation.Nullable LocalDate ipo) {
    
    this.ipo = ipo;
    return this;
  }

  /**
   * IPO date.
   * @return ipo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IPO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getIpo() {
    return ipo;
  }


  @JsonProperty(JSON_PROPERTY_IPO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIpo(@javax.annotation.Nullable LocalDate ipo) {
    this.ipo = ipo;
  }

  public CompanyProfile marketCapitalization(@javax.annotation.Nullable Float marketCapitalization) {
    
    this.marketCapitalization = marketCapitalization;
    return this;
  }

  /**
   * Market Capitalization.
   * @return marketCapitalization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKET_CAPITALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMarketCapitalization() {
    return marketCapitalization;
  }


  @JsonProperty(JSON_PROPERTY_MARKET_CAPITALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapitalization(@javax.annotation.Nullable Float marketCapitalization) {
    this.marketCapitalization = marketCapitalization;
  }

  public CompanyProfile shareOutstanding(@javax.annotation.Nullable Float shareOutstanding) {
    
    this.shareOutstanding = shareOutstanding;
    return this;
  }

  /**
   * Number of oustanding shares.
   * @return shareOutstanding
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARE_OUTSTANDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getShareOutstanding() {
    return shareOutstanding;
  }


  @JsonProperty(JSON_PROPERTY_SHARE_OUTSTANDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShareOutstanding(@javax.annotation.Nullable Float shareOutstanding) {
    this.shareOutstanding = shareOutstanding;
  }

  public CompanyProfile employeeTotal(@javax.annotation.Nullable Float employeeTotal) {
    
    this.employeeTotal = employeeTotal;
    return this;
  }

  /**
   * Number of employee.
   * @return employeeTotal
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMPLOYEE_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getEmployeeTotal() {
    return employeeTotal;
  }


  @JsonProperty(JSON_PROPERTY_EMPLOYEE_TOTAL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmployeeTotal(@javax.annotation.Nullable Float employeeTotal) {
    this.employeeTotal = employeeTotal;
  }

  public CompanyProfile logo(@javax.annotation.Nullable String logo) {
    
    this.logo = logo;
    return this;
  }

  /**
   * Logo image.
   * @return logo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLogo() {
    return logo;
  }


  @JsonProperty(JSON_PROPERTY_LOGO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLogo(@javax.annotation.Nullable String logo) {
    this.logo = logo;
  }

  public CompanyProfile finnhubIndustry(@javax.annotation.Nullable String finnhubIndustry) {
    
    this.finnhubIndustry = finnhubIndustry;
    return this;
  }

  /**
   * Finnhub industry classification.
   * @return finnhubIndustry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FINNHUB_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFinnhubIndustry() {
    return finnhubIndustry;
  }


  @JsonProperty(JSON_PROPERTY_FINNHUB_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFinnhubIndustry(@javax.annotation.Nullable String finnhubIndustry) {
    this.finnhubIndustry = finnhubIndustry;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyProfile companyProfile = (CompanyProfile) o;
    return Objects.equals(this.alias, companyProfile.alias) &&
        Objects.equals(this.address, companyProfile.address) &&
        Objects.equals(this.city, companyProfile.city) &&
        Objects.equals(this.country, companyProfile.country) &&
        Objects.equals(this.currency, companyProfile.currency) &&
        Objects.equals(this.estimateCurrency, companyProfile.estimateCurrency) &&
        Objects.equals(this.marketCapCurrency, companyProfile.marketCapCurrency) &&
        Objects.equals(this.cusip, companyProfile.cusip) &&
        Objects.equals(this.sedol, companyProfile.sedol) &&
        Objects.equals(this.description, companyProfile.description) &&
        Objects.equals(this.exchange, companyProfile.exchange) &&
        Objects.equals(this.ggroup, companyProfile.ggroup) &&
        Objects.equals(this.gind, companyProfile.gind) &&
        Objects.equals(this.gsector, companyProfile.gsector) &&
        Objects.equals(this.gsubind, companyProfile.gsubind) &&
        Objects.equals(this.isin, companyProfile.isin) &&
        Objects.equals(this.lei, companyProfile.lei) &&
        Objects.equals(this.irUrl, companyProfile.irUrl) &&
        Objects.equals(this.naicsNationalIndustry, companyProfile.naicsNationalIndustry) &&
        Objects.equals(this.naics, companyProfile.naics) &&
        Objects.equals(this.naicsSector, companyProfile.naicsSector) &&
        Objects.equals(this.naicsSubsector, companyProfile.naicsSubsector) &&
        Objects.equals(this.name, companyProfile.name) &&
        Objects.equals(this.phone, companyProfile.phone) &&
        Objects.equals(this.state, companyProfile.state) &&
        Objects.equals(this.ticker, companyProfile.ticker) &&
        Objects.equals(this.weburl, companyProfile.weburl) &&
        Objects.equals(this.ipo, companyProfile.ipo) &&
        Objects.equals(this.marketCapitalization, companyProfile.marketCapitalization) &&
        Objects.equals(this.shareOutstanding, companyProfile.shareOutstanding) &&
        Objects.equals(this.employeeTotal, companyProfile.employeeTotal) &&
        Objects.equals(this.logo, companyProfile.logo) &&
        Objects.equals(this.finnhubIndustry, companyProfile.finnhubIndustry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alias, address, city, country, currency, estimateCurrency, marketCapCurrency, cusip, sedol, description, exchange, ggroup, gind, gsector, gsubind, isin, lei, irUrl, naicsNationalIndustry, naics, naicsSector, naicsSubsector, name, phone, state, ticker, weburl, ipo, marketCapitalization, shareOutstanding, employeeTotal, logo, finnhubIndustry);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyProfile {\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    estimateCurrency: ").append(toIndentedString(estimateCurrency)).append("\n");
    sb.append("    marketCapCurrency: ").append(toIndentedString(marketCapCurrency)).append("\n");
    sb.append("    cusip: ").append(toIndentedString(cusip)).append("\n");
    sb.append("    sedol: ").append(toIndentedString(sedol)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    ggroup: ").append(toIndentedString(ggroup)).append("\n");
    sb.append("    gind: ").append(toIndentedString(gind)).append("\n");
    sb.append("    gsector: ").append(toIndentedString(gsector)).append("\n");
    sb.append("    gsubind: ").append(toIndentedString(gsubind)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    lei: ").append(toIndentedString(lei)).append("\n");
    sb.append("    irUrl: ").append(toIndentedString(irUrl)).append("\n");
    sb.append("    naicsNationalIndustry: ").append(toIndentedString(naicsNationalIndustry)).append("\n");
    sb.append("    naics: ").append(toIndentedString(naics)).append("\n");
    sb.append("    naicsSector: ").append(toIndentedString(naicsSector)).append("\n");
    sb.append("    naicsSubsector: ").append(toIndentedString(naicsSubsector)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    ticker: ").append(toIndentedString(ticker)).append("\n");
    sb.append("    weburl: ").append(toIndentedString(weburl)).append("\n");
    sb.append("    ipo: ").append(toIndentedString(ipo)).append("\n");
    sb.append("    marketCapitalization: ").append(toIndentedString(marketCapitalization)).append("\n");
    sb.append("    shareOutstanding: ").append(toIndentedString(shareOutstanding)).append("\n");
    sb.append("    employeeTotal: ").append(toIndentedString(employeeTotal)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    finnhubIndustry: ").append(toIndentedString(finnhubIndustry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

