/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CompanyESG
 */
@JsonPropertyOrder({
  CompanyESG.JSON_PROPERTY_SYMBOL,
  CompanyESG.JSON_PROPERTY_TOTAL_E_S_G_SCORE,
  CompanyESG.JSON_PROPERTY_ENVIRONMENT_SCORE,
  CompanyESG.JSON_PROPERTY_GOVERNANCE_SCORE,
  CompanyESG.JSON_PROPERTY_SOCIAL_SCORE,
  CompanyESG.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CompanyESG {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_TOTAL_E_S_G_SCORE = "totalESGScore";
  @javax.annotation.Nullable
  private Float totalESGScore;

  public static final String JSON_PROPERTY_ENVIRONMENT_SCORE = "environmentScore";
  @javax.annotation.Nullable
  private Float environmentScore;

  public static final String JSON_PROPERTY_GOVERNANCE_SCORE = "governanceScore";
  @javax.annotation.Nullable
  private Float governanceScore;

  public static final String JSON_PROPERTY_SOCIAL_SCORE = "socialScore";
  @javax.annotation.Nullable
  private Float socialScore;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private Object data;

  public CompanyESG() {
  }

  public CompanyESG symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * symbol
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public CompanyESG totalESGScore(@javax.annotation.Nullable Float totalESGScore) {
    
    this.totalESGScore = totalESGScore;
    return this;
  }

  /**
   * Total ESG Score
   * @return totalESGScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_E_S_G_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getTotalESGScore() {
    return totalESGScore;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_E_S_G_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalESGScore(@javax.annotation.Nullable Float totalESGScore) {
    this.totalESGScore = totalESGScore;
  }

  public CompanyESG environmentScore(@javax.annotation.Nullable Float environmentScore) {
    
    this.environmentScore = environmentScore;
    return this;
  }

  /**
   * Environment Score
   * @return environmentScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENVIRONMENT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getEnvironmentScore() {
    return environmentScore;
  }


  @JsonProperty(JSON_PROPERTY_ENVIRONMENT_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvironmentScore(@javax.annotation.Nullable Float environmentScore) {
    this.environmentScore = environmentScore;
  }

  public CompanyESG governanceScore(@javax.annotation.Nullable Float governanceScore) {
    
    this.governanceScore = governanceScore;
    return this;
  }

  /**
   * Governance Score
   * @return governanceScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GOVERNANCE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getGovernanceScore() {
    return governanceScore;
  }


  @JsonProperty(JSON_PROPERTY_GOVERNANCE_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGovernanceScore(@javax.annotation.Nullable Float governanceScore) {
    this.governanceScore = governanceScore;
  }

  public CompanyESG socialScore(@javax.annotation.Nullable Float socialScore) {
    
    this.socialScore = socialScore;
    return this;
  }

  /**
   * Social Score
   * @return socialScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOCIAL_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getSocialScore() {
    return socialScore;
  }


  @JsonProperty(JSON_PROPERTY_SOCIAL_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSocialScore(@javax.annotation.Nullable Float socialScore) {
    this.socialScore = socialScore;
  }

  public CompanyESG data(@javax.annotation.Nullable Object data) {
    
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable Object data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyESG companyESG = (CompanyESG) o;
    return Objects.equals(this.symbol, companyESG.symbol) &&
        Objects.equals(this.totalESGScore, companyESG.totalESGScore) &&
        Objects.equals(this.environmentScore, companyESG.environmentScore) &&
        Objects.equals(this.governanceScore, companyESG.governanceScore) &&
        Objects.equals(this.socialScore, companyESG.socialScore) &&
        Objects.equals(this.data, companyESG.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, totalESGScore, environmentScore, governanceScore, socialScore, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyESG {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    totalESGScore: ").append(toIndentedString(totalESGScore)).append("\n");
    sb.append("    environmentScore: ").append(toIndentedString(environmentScore)).append("\n");
    sb.append("    governanceScore: ").append(toIndentedString(governanceScore)).append("\n");
    sb.append("    socialScore: ").append(toIndentedString(socialScore)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

