/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CompanyNewsStatistics
 */
@JsonPropertyOrder({
  CompanyNewsStatistics.JSON_PROPERTY_ARTICLES_IN_LAST_WEEK,
  CompanyNewsStatistics.JSON_PROPERTY_BUZZ,
  CompanyNewsStatistics.JSON_PROPERTY_WEEKLY_AVERAGE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class CompanyNewsStatistics {
  public static final String JSON_PROPERTY_ARTICLES_IN_LAST_WEEK = "articlesInLastWeek";
  @javax.annotation.Nullable
  private Long articlesInLastWeek;

  public static final String JSON_PROPERTY_BUZZ = "buzz";
  @javax.annotation.Nullable
  private Float buzz;

  public static final String JSON_PROPERTY_WEEKLY_AVERAGE = "weeklyAverage";
  @javax.annotation.Nullable
  private Float weeklyAverage;

  public CompanyNewsStatistics() {
  }

  public CompanyNewsStatistics articlesInLastWeek(@javax.annotation.Nullable Long articlesInLastWeek) {
    
    this.articlesInLastWeek = articlesInLastWeek;
    return this;
  }

  /**
   * 
   * @return articlesInLastWeek
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ARTICLES_IN_LAST_WEEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getArticlesInLastWeek() {
    return articlesInLastWeek;
  }


  @JsonProperty(JSON_PROPERTY_ARTICLES_IN_LAST_WEEK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArticlesInLastWeek(@javax.annotation.Nullable Long articlesInLastWeek) {
    this.articlesInLastWeek = articlesInLastWeek;
  }

  public CompanyNewsStatistics buzz(@javax.annotation.Nullable Float buzz) {
    
    this.buzz = buzz;
    return this;
  }

  /**
   * 
   * @return buzz
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUZZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getBuzz() {
    return buzz;
  }


  @JsonProperty(JSON_PROPERTY_BUZZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuzz(@javax.annotation.Nullable Float buzz) {
    this.buzz = buzz;
  }

  public CompanyNewsStatistics weeklyAverage(@javax.annotation.Nullable Float weeklyAverage) {
    
    this.weeklyAverage = weeklyAverage;
    return this;
  }

  /**
   * 
   * @return weeklyAverage
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WEEKLY_AVERAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getWeeklyAverage() {
    return weeklyAverage;
  }


  @JsonProperty(JSON_PROPERTY_WEEKLY_AVERAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWeeklyAverage(@javax.annotation.Nullable Float weeklyAverage) {
    this.weeklyAverage = weeklyAverage;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyNewsStatistics companyNewsStatistics = (CompanyNewsStatistics) o;
    return Objects.equals(this.articlesInLastWeek, companyNewsStatistics.articlesInLastWeek) &&
        Objects.equals(this.buzz, companyNewsStatistics.buzz) &&
        Objects.equals(this.weeklyAverage, companyNewsStatistics.weeklyAverage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(articlesInLastWeek, buzz, weeklyAverage);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyNewsStatistics {\n");
    sb.append("    articlesInLastWeek: ").append(toIndentedString(articlesInLastWeek)).append("\n");
    sb.append("    buzz: ").append(toIndentedString(buzz)).append("\n");
    sb.append("    weeklyAverage: ").append(toIndentedString(weeklyAverage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

