/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CongressionalTransaction
 */
@JsonPropertyOrder({
  CongressionalTransaction.JSON_PROPERTY_AMOUNT_FROM,
  CongressionalTransaction.JSON_PROPERTY_AMOUNT_TO,
  CongressionalTransaction.JSON_PROPERTY_ASSET_NAME,
  CongressionalTransaction.JSON_PROPERTY_FILING_DATE,
  CongressionalTransaction.JSON_PROPERTY_NAME,
  CongressionalTransaction.JSON_PROPERTY_OWNER_TYPE,
  CongressionalTransaction.JSON_PROPERTY_POSITION,
  CongressionalTransaction.JSON_PROPERTY_SYMBOL,
  CongressionalTransaction.JSON_PROPERTY_TRANSACTION_DATE,
  CongressionalTransaction.JSON_PROPERTY_TRANSACTION_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class CongressionalTransaction {
  public static final String JSON_PROPERTY_AMOUNT_FROM = "amountFrom";
  @javax.annotation.Nullable
  private Float amountFrom;

  public static final String JSON_PROPERTY_AMOUNT_TO = "amountTo";
  @javax.annotation.Nullable
  private Float amountTo;

  public static final String JSON_PROPERTY_ASSET_NAME = "assetName";
  @javax.annotation.Nullable
  private String assetName;

  public static final String JSON_PROPERTY_FILING_DATE = "filingDate";
  @javax.annotation.Nullable
  private String filingDate;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_OWNER_TYPE = "ownerType";
  @javax.annotation.Nullable
  private String ownerType;

  public static final String JSON_PROPERTY_POSITION = "position";
  @javax.annotation.Nullable
  private String position;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_TRANSACTION_DATE = "transactionDate";
  @javax.annotation.Nullable
  private String transactionDate;

  public static final String JSON_PROPERTY_TRANSACTION_TYPE = "transactionType";
  @javax.annotation.Nullable
  private String transactionType;

  public CongressionalTransaction() {
  }

  public CongressionalTransaction amountFrom(@javax.annotation.Nullable Float amountFrom) {
    
    this.amountFrom = amountFrom;
    return this;
  }

  /**
   * Transaction amount from.
   * @return amountFrom
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAmountFrom() {
    return amountFrom;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountFrom(@javax.annotation.Nullable Float amountFrom) {
    this.amountFrom = amountFrom;
  }

  public CongressionalTransaction amountTo(@javax.annotation.Nullable Float amountTo) {
    
    this.amountTo = amountTo;
    return this;
  }

  /**
   * Transaction amount to.
   * @return amountTo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getAmountTo() {
    return amountTo;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountTo(@javax.annotation.Nullable Float amountTo) {
    this.amountTo = amountTo;
  }

  public CongressionalTransaction assetName(@javax.annotation.Nullable String assetName) {
    
    this.assetName = assetName;
    return this;
  }

  /**
   * Asset name.
   * @return assetName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ASSET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssetName() {
    return assetName;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetName(@javax.annotation.Nullable String assetName) {
    this.assetName = assetName;
  }

  public CongressionalTransaction filingDate(@javax.annotation.Nullable String filingDate) {
    
    this.filingDate = filingDate;
    return this;
  }

  /**
   * Filing date.
   * @return filingDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilingDate() {
    return filingDate;
  }


  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilingDate(@javax.annotation.Nullable String filingDate) {
    this.filingDate = filingDate;
  }

  public CongressionalTransaction name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Name of the representative.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public CongressionalTransaction ownerType(@javax.annotation.Nullable String ownerType) {
    
    this.ownerType = ownerType;
    return this;
  }

  /**
   * Owner Type.
   * @return ownerType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOwnerType() {
    return ownerType;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerType(@javax.annotation.Nullable String ownerType) {
    this.ownerType = ownerType;
  }

  public CongressionalTransaction position(@javax.annotation.Nullable String position) {
    
    this.position = position;
    return this;
  }

  /**
   * Position.
   * @return position
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPosition() {
    return position;
  }


  @JsonProperty(JSON_PROPERTY_POSITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPosition(@javax.annotation.Nullable String position) {
    this.position = position;
  }

  public CongressionalTransaction symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Symbol.
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public CongressionalTransaction transactionDate(@javax.annotation.Nullable String transactionDate) {
    
    this.transactionDate = transactionDate;
    return this;
  }

  /**
   * Transaction date.
   * @return transactionDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionDate() {
    return transactionDate;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionDate(@javax.annotation.Nullable String transactionDate) {
    this.transactionDate = transactionDate;
  }

  public CongressionalTransaction transactionType(@javax.annotation.Nullable String transactionType) {
    
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Transaction type &lt;code&gt;Sale&lt;/code&gt; or &lt;code&gt;Purchase&lt;/code&gt;.
   * @return transactionType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransactionType() {
    return transactionType;
  }


  @JsonProperty(JSON_PROPERTY_TRANSACTION_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransactionType(@javax.annotation.Nullable String transactionType) {
    this.transactionType = transactionType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CongressionalTransaction congressionalTransaction = (CongressionalTransaction) o;
    return Objects.equals(this.amountFrom, congressionalTransaction.amountFrom) &&
        Objects.equals(this.amountTo, congressionalTransaction.amountTo) &&
        Objects.equals(this.assetName, congressionalTransaction.assetName) &&
        Objects.equals(this.filingDate, congressionalTransaction.filingDate) &&
        Objects.equals(this.name, congressionalTransaction.name) &&
        Objects.equals(this.ownerType, congressionalTransaction.ownerType) &&
        Objects.equals(this.position, congressionalTransaction.position) &&
        Objects.equals(this.symbol, congressionalTransaction.symbol) &&
        Objects.equals(this.transactionDate, congressionalTransaction.transactionDate) &&
        Objects.equals(this.transactionType, congressionalTransaction.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountFrom, amountTo, assetName, filingDate, name, ownerType, position, symbol, transactionDate, transactionType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CongressionalTransaction {\n");
    sb.append("    amountFrom: ").append(toIndentedString(amountFrom)).append("\n");
    sb.append("    amountTo: ").append(toIndentedString(amountTo)).append("\n");
    sb.append("    assetName: ").append(toIndentedString(assetName)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerType: ").append(toIndentedString(ownerType)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    transactionDate: ").append(toIndentedString(transactionDate)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

