/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CountryMetadata
 */
@JsonPropertyOrder({
  CountryMetadata.JSON_PROPERTY_COUNTRY,
  CountryMetadata.JSON_PROPERTY_CODE2,
  CountryMetadata.JSON_PROPERTY_CODE3,
  CountryMetadata.JSON_PROPERTY_CODE_NO,
  CountryMetadata.JSON_PROPERTY_CURRENCY,
  CountryMetadata.JSON_PROPERTY_CURRENCY_CODE,
  CountryMetadata.JSON_PROPERTY_REGION,
  CountryMetadata.JSON_PROPERTY_SUB_REGION,
  CountryMetadata.JSON_PROPERTY_RATING,
  CountryMetadata.JSON_PROPERTY_DEFAULT_SPREAD,
  CountryMetadata.JSON_PROPERTY_COUNTRY_RISK_PREMIUM,
  CountryMetadata.JSON_PROPERTY_EQUITY_RISK_PREMIUM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class CountryMetadata {
  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_CODE2 = "code2";
  @javax.annotation.Nullable
  private String code2;

  public static final String JSON_PROPERTY_CODE3 = "code3";
  @javax.annotation.Nullable
  private String code3;

  public static final String JSON_PROPERTY_CODE_NO = "codeNo";
  @javax.annotation.Nullable
  private String codeNo;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  @javax.annotation.Nullable
  private String currency;

  public static final String JSON_PROPERTY_CURRENCY_CODE = "currencyCode";
  @javax.annotation.Nullable
  private String currencyCode;

  public static final String JSON_PROPERTY_REGION = "region";
  @javax.annotation.Nullable
  private String region;

  public static final String JSON_PROPERTY_SUB_REGION = "subRegion";
  @javax.annotation.Nullable
  private String subRegion;

  public static final String JSON_PROPERTY_RATING = "rating";
  @javax.annotation.Nullable
  private String rating;

  public static final String JSON_PROPERTY_DEFAULT_SPREAD = "defaultSpread";
  @javax.annotation.Nullable
  private Float defaultSpread;

  public static final String JSON_PROPERTY_COUNTRY_RISK_PREMIUM = "countryRiskPremium";
  @javax.annotation.Nullable
  private Float countryRiskPremium;

  public static final String JSON_PROPERTY_EQUITY_RISK_PREMIUM = "equityRiskPremium";
  @javax.annotation.Nullable
  private Float equityRiskPremium;

  public CountryMetadata() {
  }

  public CountryMetadata country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Country name
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public CountryMetadata code2(@javax.annotation.Nullable String code2) {
    
    this.code2 = code2;
    return this;
  }

  /**
   * Alpha 2 code
   * @return code2
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode2() {
    return code2;
  }


  @JsonProperty(JSON_PROPERTY_CODE2)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode2(@javax.annotation.Nullable String code2) {
    this.code2 = code2;
  }

  public CountryMetadata code3(@javax.annotation.Nullable String code3) {
    
    this.code3 = code3;
    return this;
  }

  /**
   * Alpha 3 code
   * @return code3
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode3() {
    return code3;
  }


  @JsonProperty(JSON_PROPERTY_CODE3)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode3(@javax.annotation.Nullable String code3) {
    this.code3 = code3;
  }

  public CountryMetadata codeNo(@javax.annotation.Nullable String codeNo) {
    
    this.codeNo = codeNo;
    return this;
  }

  /**
   * UN code
   * @return codeNo
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodeNo() {
    return codeNo;
  }


  @JsonProperty(JSON_PROPERTY_CODE_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeNo(@javax.annotation.Nullable String codeNo) {
    this.codeNo = codeNo;
  }

  public CountryMetadata currency(@javax.annotation.Nullable String currency) {
    
    this.currency = currency;
    return this;
  }

  /**
   * Currency name
   * @return currency
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrency() {
    return currency;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrency(@javax.annotation.Nullable String currency) {
    this.currency = currency;
  }

  public CountryMetadata currencyCode(@javax.annotation.Nullable String currencyCode) {
    
    this.currencyCode = currencyCode;
    return this;
  }

  /**
   * Currency code
   * @return currencyCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCurrencyCode() {
    return currencyCode;
  }


  @JsonProperty(JSON_PROPERTY_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCurrencyCode(@javax.annotation.Nullable String currencyCode) {
    this.currencyCode = currencyCode;
  }

  public CountryMetadata region(@javax.annotation.Nullable String region) {
    
    this.region = region;
    return this;
  }

  /**
   * Region
   * @return region
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegion() {
    return region;
  }


  @JsonProperty(JSON_PROPERTY_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = region;
  }

  public CountryMetadata subRegion(@javax.annotation.Nullable String subRegion) {
    
    this.subRegion = subRegion;
    return this;
  }

  /**
   * Sub-Region
   * @return subRegion
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSubRegion() {
    return subRegion;
  }


  @JsonProperty(JSON_PROPERTY_SUB_REGION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubRegion(@javax.annotation.Nullable String subRegion) {
    this.subRegion = subRegion;
  }

  public CountryMetadata rating(@javax.annotation.Nullable String rating) {
    
    this.rating = rating;
    return this;
  }

  /**
   * Moody&#39;s credit risk rating.
   * @return rating
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRating() {
    return rating;
  }


  @JsonProperty(JSON_PROPERTY_RATING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRating(@javax.annotation.Nullable String rating) {
    this.rating = rating;
  }

  public CountryMetadata defaultSpread(@javax.annotation.Nullable Float defaultSpread) {
    
    this.defaultSpread = defaultSpread;
    return this;
  }

  /**
   * Default spread
   * @return defaultSpread
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEFAULT_SPREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDefaultSpread() {
    return defaultSpread;
  }


  @JsonProperty(JSON_PROPERTY_DEFAULT_SPREAD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultSpread(@javax.annotation.Nullable Float defaultSpread) {
    this.defaultSpread = defaultSpread;
  }

  public CountryMetadata countryRiskPremium(@javax.annotation.Nullable Float countryRiskPremium) {
    
    this.countryRiskPremium = countryRiskPremium;
    return this;
  }

  /**
   * Country risk premium
   * @return countryRiskPremium
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY_RISK_PREMIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getCountryRiskPremium() {
    return countryRiskPremium;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_RISK_PREMIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountryRiskPremium(@javax.annotation.Nullable Float countryRiskPremium) {
    this.countryRiskPremium = countryRiskPremium;
  }

  public CountryMetadata equityRiskPremium(@javax.annotation.Nullable Float equityRiskPremium) {
    
    this.equityRiskPremium = equityRiskPremium;
    return this;
  }

  /**
   * Equity risk premium
   * @return equityRiskPremium
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EQUITY_RISK_PREMIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getEquityRiskPremium() {
    return equityRiskPremium;
  }


  @JsonProperty(JSON_PROPERTY_EQUITY_RISK_PREMIUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEquityRiskPremium(@javax.annotation.Nullable Float equityRiskPremium) {
    this.equityRiskPremium = equityRiskPremium;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CountryMetadata countryMetadata = (CountryMetadata) o;
    return Objects.equals(this.country, countryMetadata.country) &&
        Objects.equals(this.code2, countryMetadata.code2) &&
        Objects.equals(this.code3, countryMetadata.code3) &&
        Objects.equals(this.codeNo, countryMetadata.codeNo) &&
        Objects.equals(this.currency, countryMetadata.currency) &&
        Objects.equals(this.currencyCode, countryMetadata.currencyCode) &&
        Objects.equals(this.region, countryMetadata.region) &&
        Objects.equals(this.subRegion, countryMetadata.subRegion) &&
        Objects.equals(this.rating, countryMetadata.rating) &&
        Objects.equals(this.defaultSpread, countryMetadata.defaultSpread) &&
        Objects.equals(this.countryRiskPremium, countryMetadata.countryRiskPremium) &&
        Objects.equals(this.equityRiskPremium, countryMetadata.equityRiskPremium);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, code2, code3, codeNo, currency, currencyCode, region, subRegion, rating, defaultSpread, countryRiskPremium, equityRiskPremium);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CountryMetadata {\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    code2: ").append(toIndentedString(code2)).append("\n");
    sb.append("    code3: ").append(toIndentedString(code3)).append("\n");
    sb.append("    codeNo: ").append(toIndentedString(codeNo)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    currencyCode: ").append(toIndentedString(currencyCode)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    subRegion: ").append(toIndentedString(subRegion)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    defaultSpread: ").append(toIndentedString(defaultSpread)).append("\n");
    sb.append("    countryRiskPremium: ").append(toIndentedString(countryRiskPremium)).append("\n");
    sb.append("    equityRiskPremium: ").append(toIndentedString(equityRiskPremium)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

