/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * EarningsCallLiveResult
 */
@JsonPropertyOrder({
  EarningsCallLiveResult.JSON_PROPERTY_SYMBOL,
  EarningsCallLiveResult.JSON_PROPERTY_EVENT,
  EarningsCallLiveResult.JSON_PROPERTY_TIME,
  EarningsCallLiveResult.JSON_PROPERTY_YEAR,
  EarningsCallLiveResult.JSON_PROPERTY_QUARTER,
  EarningsCallLiveResult.JSON_PROPERTY_LIVE_AUDIO,
  EarningsCallLiveResult.JSON_PROPERTY_RECORDING
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class EarningsCallLiveResult {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_EVENT = "event";
  @javax.annotation.Nullable
  private String event;

  public static final String JSON_PROPERTY_TIME = "time";
  @javax.annotation.Nullable
  private String time;

  public static final String JSON_PROPERTY_YEAR = "year";
  @javax.annotation.Nullable
  private Long year;

  public static final String JSON_PROPERTY_QUARTER = "quarter";
  @javax.annotation.Nullable
  private Long quarter;

  public static final String JSON_PROPERTY_LIVE_AUDIO = "liveAudio";
  @javax.annotation.Nullable
  private String liveAudio;

  public static final String JSON_PROPERTY_RECORDING = "recording";
  @javax.annotation.Nullable
  private String recording;

  public EarningsCallLiveResult() {
  }

  public EarningsCallLiveResult symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Symbol.
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public EarningsCallLiveResult event(@javax.annotation.Nullable String event) {
    
    this.event = event;
    return this;
  }

  /**
   * Event name.
   * @return event
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEvent() {
    return event;
  }


  @JsonProperty(JSON_PROPERTY_EVENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvent(@javax.annotation.Nullable String event) {
    this.event = event;
  }

  public EarningsCallLiveResult time(@javax.annotation.Nullable String time) {
    
    this.time = time;
    return this;
  }

  /**
   * Date time in UTC.
   * @return time
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTime() {
    return time;
  }


  @JsonProperty(JSON_PROPERTY_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTime(@javax.annotation.Nullable String time) {
    this.time = time;
  }

  public EarningsCallLiveResult year(@javax.annotation.Nullable Long year) {
    
    this.year = year;
    return this;
  }

  /**
   * Earnings year.
   * @return year
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getYear() {
    return year;
  }


  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYear(@javax.annotation.Nullable Long year) {
    this.year = year;
  }

  public EarningsCallLiveResult quarter(@javax.annotation.Nullable Long quarter) {
    
    this.quarter = quarter;
    return this;
  }

  /**
   * Earnings quarter.
   * @return quarter
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUARTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getQuarter() {
    return quarter;
  }


  @JsonProperty(JSON_PROPERTY_QUARTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuarter(@javax.annotation.Nullable Long quarter) {
    this.quarter = quarter;
  }

  public EarningsCallLiveResult liveAudio(@javax.annotation.Nullable String liveAudio) {
    
    this.liveAudio = liveAudio;
    return this;
  }

  /**
   * Live audio streaming file.
   * @return liveAudio
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIVE_AUDIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLiveAudio() {
    return liveAudio;
  }


  @JsonProperty(JSON_PROPERTY_LIVE_AUDIO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLiveAudio(@javax.annotation.Nullable String liveAudio) {
    this.liveAudio = liveAudio;
  }

  public EarningsCallLiveResult recording(@javax.annotation.Nullable String recording) {
    
    this.recording = recording;
    return this;
  }

  /**
   * Recoding in mp3 format.
   * @return recording
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECORDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRecording() {
    return recording;
  }


  @JsonProperty(JSON_PROPERTY_RECORDING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecording(@javax.annotation.Nullable String recording) {
    this.recording = recording;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EarningsCallLiveResult earningsCallLiveResult = (EarningsCallLiveResult) o;
    return Objects.equals(this.symbol, earningsCallLiveResult.symbol) &&
        Objects.equals(this.event, earningsCallLiveResult.event) &&
        Objects.equals(this.time, earningsCallLiveResult.time) &&
        Objects.equals(this.year, earningsCallLiveResult.year) &&
        Objects.equals(this.quarter, earningsCallLiveResult.quarter) &&
        Objects.equals(this.liveAudio, earningsCallLiveResult.liveAudio) &&
        Objects.equals(this.recording, earningsCallLiveResult.recording);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, event, time, year, quarter, liveAudio, recording);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EarningsCallLiveResult {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
    sb.append("    liveAudio: ").append(toIndentedString(liveAudio)).append("\n");
    sb.append("    recording: ").append(toIndentedString(recording)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

