/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ETFSectorExposureData
 */
@JsonPropertyOrder({
  ETFSectorExposureData.JSON_PROPERTY_INDUSTRY,
  ETFSectorExposureData.JSON_PROPERTY_EXPOSURE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ETFSectorExposureData {
  public static final String JSON_PROPERTY_INDUSTRY = "industry";
  @javax.annotation.Nullable
  private String industry;

  public static final String JSON_PROPERTY_EXPOSURE = "exposure";
  @javax.annotation.Nullable
  private Float exposure;

  public ETFSectorExposureData() {
  }

  public ETFSectorExposureData industry(@javax.annotation.Nullable String industry) {
    
    this.industry = industry;
    return this;
  }

  /**
   * Industry
   * @return industry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndustry() {
    return industry;
  }


  @JsonProperty(JSON_PROPERTY_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
  }

  public ETFSectorExposureData exposure(@javax.annotation.Nullable Float exposure) {
    
    this.exposure = exposure;
    return this;
  }

  /**
   * Percent of exposure.
   * @return exposure
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPOSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getExposure() {
    return exposure;
  }


  @JsonProperty(JSON_PROPERTY_EXPOSURE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExposure(@javax.annotation.Nullable Float exposure) {
    this.exposure = exposure;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ETFSectorExposureData etFSectorExposureData = (ETFSectorExposureData) o;
    return Objects.equals(this.industry, etFSectorExposureData.industry) &&
        Objects.equals(this.exposure, etFSectorExposureData.exposure);
  }

  @Override
  public int hashCode() {
    return Objects.hash(industry, exposure);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ETFSectorExposureData {\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    exposure: ").append(toIndentedString(exposure)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

