/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FilingResponse
 */
@JsonPropertyOrder({
  FilingResponse.JSON_PROPERTY_FILING_ID,
  FilingResponse.JSON_PROPERTY_TITLE,
  FilingResponse.JSON_PROPERTY_FILER_ID,
  FilingResponse.JSON_PROPERTY_SYMBOL,
  FilingResponse.JSON_PROPERTY_NAME,
  FilingResponse.JSON_PROPERTY_ACCEPTANCE_DATE,
  FilingResponse.JSON_PROPERTY_FILED_DATE,
  FilingResponse.JSON_PROPERTY_REPORT_DATE,
  FilingResponse.JSON_PROPERTY_FORM,
  FilingResponse.JSON_PROPERTY_AMEND,
  FilingResponse.JSON_PROPERTY_SOURCE,
  FilingResponse.JSON_PROPERTY_PAGE_COUNT,
  FilingResponse.JSON_PROPERTY_DOCUMENT_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class FilingResponse {
  public static final String JSON_PROPERTY_FILING_ID = "filingId";
  @javax.annotation.Nullable
  private String filingId;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_FILER_ID = "filerId";
  @javax.annotation.Nullable
  private String filerId;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private Object symbol;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_ACCEPTANCE_DATE = "acceptanceDate";
  @javax.annotation.Nullable
  private String acceptanceDate;

  public static final String JSON_PROPERTY_FILED_DATE = "filedDate";
  @javax.annotation.Nullable
  private String filedDate;

  public static final String JSON_PROPERTY_REPORT_DATE = "reportDate";
  @javax.annotation.Nullable
  private String reportDate;

  public static final String JSON_PROPERTY_FORM = "form";
  @javax.annotation.Nullable
  private String form;

  public static final String JSON_PROPERTY_AMEND = "amend";
  @javax.annotation.Nullable
  private Boolean amend;

  public static final String JSON_PROPERTY_SOURCE = "source";
  @javax.annotation.Nullable
  private String source;

  public static final String JSON_PROPERTY_PAGE_COUNT = "pageCount";
  @javax.annotation.Nullable
  private Integer pageCount;

  public static final String JSON_PROPERTY_DOCUMENT_COUNT = "documentCount";
  @javax.annotation.Nullable
  private Integer documentCount;

  public FilingResponse() {
  }

  public FilingResponse filingId(@javax.annotation.Nullable String filingId) {
    
    this.filingId = filingId;
    return this;
  }

  /**
   * Filing Id in Alpharesearch platform
   * @return filingId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilingId() {
    return filingId;
  }


  @JsonProperty(JSON_PROPERTY_FILING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilingId(@javax.annotation.Nullable String filingId) {
    this.filingId = filingId;
  }

  public FilingResponse title(@javax.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Filing title
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }

  public FilingResponse filerId(@javax.annotation.Nullable String filerId) {
    
    this.filerId = filerId;
    return this;
  }

  /**
   * Id of the entity submitted the filing
   * @return filerId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilerId() {
    return filerId;
  }


  @JsonProperty(JSON_PROPERTY_FILER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilerId(@javax.annotation.Nullable String filerId) {
    this.filerId = filerId;
  }

  public FilingResponse symbol(@javax.annotation.Nullable Object symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * List of symbol associate with this filing
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable Object symbol) {
    this.symbol = symbol;
  }

  public FilingResponse name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Filer name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public FilingResponse acceptanceDate(@javax.annotation.Nullable String acceptanceDate) {
    
    this.acceptanceDate = acceptanceDate;
    return this;
  }

  /**
   * Date the filing is submitted.
   * @return acceptanceDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCEPTANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAcceptanceDate() {
    return acceptanceDate;
  }


  @JsonProperty(JSON_PROPERTY_ACCEPTANCE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcceptanceDate(@javax.annotation.Nullable String acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
  }

  public FilingResponse filedDate(@javax.annotation.Nullable String filedDate) {
    
    this.filedDate = filedDate;
    return this;
  }

  /**
   * Date the filing is made available to the public
   * @return filedDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFiledDate() {
    return filedDate;
  }


  @JsonProperty(JSON_PROPERTY_FILED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFiledDate(@javax.annotation.Nullable String filedDate) {
    this.filedDate = filedDate;
  }

  public FilingResponse reportDate(@javax.annotation.Nullable String reportDate) {
    
    this.reportDate = reportDate;
    return this;
  }

  /**
   * Date as which the filing is reported
   * @return reportDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REPORT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReportDate() {
    return reportDate;
  }


  @JsonProperty(JSON_PROPERTY_REPORT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReportDate(@javax.annotation.Nullable String reportDate) {
    this.reportDate = reportDate;
  }

  public FilingResponse form(@javax.annotation.Nullable String form) {
    
    this.form = form;
    return this;
  }

  /**
   * Filing Form
   * @return form
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getForm() {
    return form;
  }


  @JsonProperty(JSON_PROPERTY_FORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForm(@javax.annotation.Nullable String form) {
    this.form = form;
  }

  public FilingResponse amend(@javax.annotation.Nullable Boolean amend) {
    
    this.amend = amend;
    return this;
  }

  /**
   * Amendment
   * @return amend
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMEND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getAmend() {
    return amend;
  }


  @JsonProperty(JSON_PROPERTY_AMEND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmend(@javax.annotation.Nullable Boolean amend) {
    this.amend = amend;
  }

  public FilingResponse source(@javax.annotation.Nullable String source) {
    
    this.source = source;
    return this;
  }

  /**
   * Filing Source
   * @return source
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSource() {
    return source;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSource(@javax.annotation.Nullable String source) {
    this.source = source;
  }

  public FilingResponse pageCount(@javax.annotation.Nullable Integer pageCount) {
    
    this.pageCount = pageCount;
    return this;
  }

  /**
   * Estimate number of page when printing
   * @return pageCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getPageCount() {
    return pageCount;
  }


  @JsonProperty(JSON_PROPERTY_PAGE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageCount(@javax.annotation.Nullable Integer pageCount) {
    this.pageCount = pageCount;
  }

  public FilingResponse documentCount(@javax.annotation.Nullable Integer documentCount) {
    
    this.documentCount = documentCount;
    return this;
  }

  /**
   * Number of document in this filing
   * @return documentCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getDocumentCount() {
    return documentCount;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentCount(@javax.annotation.Nullable Integer documentCount) {
    this.documentCount = documentCount;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilingResponse filingResponse = (FilingResponse) o;
    return Objects.equals(this.filingId, filingResponse.filingId) &&
        Objects.equals(this.title, filingResponse.title) &&
        Objects.equals(this.filerId, filingResponse.filerId) &&
        Objects.equals(this.symbol, filingResponse.symbol) &&
        Objects.equals(this.name, filingResponse.name) &&
        Objects.equals(this.acceptanceDate, filingResponse.acceptanceDate) &&
        Objects.equals(this.filedDate, filingResponse.filedDate) &&
        Objects.equals(this.reportDate, filingResponse.reportDate) &&
        Objects.equals(this.form, filingResponse.form) &&
        Objects.equals(this.amend, filingResponse.amend) &&
        Objects.equals(this.source, filingResponse.source) &&
        Objects.equals(this.pageCount, filingResponse.pageCount) &&
        Objects.equals(this.documentCount, filingResponse.documentCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(filingId, title, filerId, symbol, name, acceptanceDate, filedDate, reportDate, form, amend, source, pageCount, documentCount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilingResponse {\n");
    sb.append("    filingId: ").append(toIndentedString(filingId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    filerId: ").append(toIndentedString(filerId)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    acceptanceDate: ").append(toIndentedString(acceptanceDate)).append("\n");
    sb.append("    filedDate: ").append(toIndentedString(filedDate)).append("\n");
    sb.append("    reportDate: ").append(toIndentedString(reportDate)).append("\n");
    sb.append("    form: ").append(toIndentedString(form)).append("\n");
    sb.append("    amend: ").append(toIndentedString(amend)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    documentCount: ").append(toIndentedString(documentCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

