/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FundOwnershipInfo
 */
@JsonPropertyOrder({
  FundOwnershipInfo.JSON_PROPERTY_NAME,
  FundOwnershipInfo.JSON_PROPERTY_SHARE,
  FundOwnershipInfo.JSON_PROPERTY_CHANGE,
  FundOwnershipInfo.JSON_PROPERTY_FILING_DATE,
  FundOwnershipInfo.JSON_PROPERTY_PORTFOLIO_PERCENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class FundOwnershipInfo {
  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_SHARE = "share";
  @javax.annotation.Nullable
  private Long share;

  public static final String JSON_PROPERTY_CHANGE = "change";
  @javax.annotation.Nullable
  private Long change;

  public static final String JSON_PROPERTY_FILING_DATE = "filingDate";
  @javax.annotation.Nullable
  private LocalDate filingDate;

  public static final String JSON_PROPERTY_PORTFOLIO_PERCENT = "portfolioPercent";
  @javax.annotation.Nullable
  private Float portfolioPercent;

  public FundOwnershipInfo() {
  }

  public FundOwnershipInfo name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Investor&#39;s name.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public FundOwnershipInfo share(@javax.annotation.Nullable Long share) {
    
    this.share = share;
    return this;
  }

  /**
   * Number of shares held by the investor.
   * @return share
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getShare() {
    return share;
  }


  @JsonProperty(JSON_PROPERTY_SHARE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShare(@javax.annotation.Nullable Long share) {
    this.share = share;
  }

  public FundOwnershipInfo change(@javax.annotation.Nullable Long change) {
    
    this.change = change;
    return this;
  }

  /**
   * Number of share changed (net buy or sell) from the last period.
   * @return change
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getChange() {
    return change;
  }


  @JsonProperty(JSON_PROPERTY_CHANGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChange(@javax.annotation.Nullable Long change) {
    this.change = change;
  }

  public FundOwnershipInfo filingDate(@javax.annotation.Nullable LocalDate filingDate) {
    
    this.filingDate = filingDate;
    return this;
  }

  /**
   * Filing date.
   * @return filingDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LocalDate getFilingDate() {
    return filingDate;
  }


  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilingDate(@javax.annotation.Nullable LocalDate filingDate) {
    this.filingDate = filingDate;
  }

  public FundOwnershipInfo portfolioPercent(@javax.annotation.Nullable Float portfolioPercent) {
    
    this.portfolioPercent = portfolioPercent;
    return this;
  }

  /**
   * Percent of the fund&#39;s portfolio comprised of the company&#39;s share.
   * @return portfolioPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PORTFOLIO_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getPortfolioPercent() {
    return portfolioPercent;
  }


  @JsonProperty(JSON_PROPERTY_PORTFOLIO_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPortfolioPercent(@javax.annotation.Nullable Float portfolioPercent) {
    this.portfolioPercent = portfolioPercent;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FundOwnershipInfo fundOwnershipInfo = (FundOwnershipInfo) o;
    return Objects.equals(this.name, fundOwnershipInfo.name) &&
        Objects.equals(this.share, fundOwnershipInfo.share) &&
        Objects.equals(this.change, fundOwnershipInfo.change) &&
        Objects.equals(this.filingDate, fundOwnershipInfo.filingDate) &&
        Objects.equals(this.portfolioPercent, fundOwnershipInfo.portfolioPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, share, change, filingDate, portfolioPercent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FundOwnershipInfo {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    share: ").append(toIndentedString(share)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    portfolioPercent: ").append(toIndentedString(portfolioPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

