/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.IsinChangeInfo;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * IsinChange
 */
@JsonPropertyOrder({
  IsinChange.JSON_PROPERTY_FROM_DATE,
  IsinChange.JSON_PROPERTY_TO_DATE,
  IsinChange.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class IsinChange {
  public static final String JSON_PROPERTY_FROM_DATE = "fromDate";
  @javax.annotation.Nullable
  private String fromDate;

  public static final String JSON_PROPERTY_TO_DATE = "toDate";
  @javax.annotation.Nullable
  private String toDate;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<IsinChangeInfo> data = new ArrayList<>();

  public IsinChange() {
  }

  public IsinChange fromDate(@javax.annotation.Nullable String fromDate) {
    
    this.fromDate = fromDate;
    return this;
  }

  /**
   * From date.
   * @return fromDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromDate() {
    return fromDate;
  }


  @JsonProperty(JSON_PROPERTY_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromDate(@javax.annotation.Nullable String fromDate) {
    this.fromDate = fromDate;
  }

  public IsinChange toDate(@javax.annotation.Nullable String toDate) {
    
    this.toDate = toDate;
    return this;
  }

  /**
   * To date.
   * @return toDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToDate() {
    return toDate;
  }


  @JsonProperty(JSON_PROPERTY_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToDate(@javax.annotation.Nullable String toDate) {
    this.toDate = toDate;
  }

  public IsinChange data(@javax.annotation.Nullable List<IsinChangeInfo> data) {
    
    this.data = data;
    return this;
  }

  public IsinChange addDataItem(IsinChangeInfo dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Array of ISIN change events.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<IsinChangeInfo> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<IsinChangeInfo> data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IsinChange isinChange = (IsinChange) o;
    return Objects.equals(this.fromDate, isinChange.fromDate) &&
        Objects.equals(this.toDate, isinChange.toDate) &&
        Objects.equals(this.data, isinChange.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fromDate, toDate, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IsinChange {\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

