/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * KeyCustomersSuppliers
 */
@JsonPropertyOrder({
  KeyCustomersSuppliers.JSON_PROPERTY_SYMBOL,
  KeyCustomersSuppliers.JSON_PROPERTY_NAME,
  KeyCustomersSuppliers.JSON_PROPERTY_COUNTRY,
  KeyCustomersSuppliers.JSON_PROPERTY_INDUSTRY,
  KeyCustomersSuppliers.JSON_PROPERTY_CUSTOMER,
  KeyCustomersSuppliers.JSON_PROPERTY_SUPPLIER,
  KeyCustomersSuppliers.JSON_PROPERTY_ONE_MONTH_CORRELATION,
  KeyCustomersSuppliers.JSON_PROPERTY_ONE_YEAR_CORRELATION,
  KeyCustomersSuppliers.JSON_PROPERTY_SIX_MONTH_CORRELATION,
  KeyCustomersSuppliers.JSON_PROPERTY_THREE_MONTH_CORRELATION,
  KeyCustomersSuppliers.JSON_PROPERTY_TWO_WEEK_CORRELATION,
  KeyCustomersSuppliers.JSON_PROPERTY_TWO_YEAR_CORRELATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class KeyCustomersSuppliers {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_INDUSTRY = "industry";
  @javax.annotation.Nullable
  private String industry;

  public static final String JSON_PROPERTY_CUSTOMER = "customer";
  @javax.annotation.Nullable
  private Boolean customer;

  public static final String JSON_PROPERTY_SUPPLIER = "supplier";
  @javax.annotation.Nullable
  private Boolean supplier;

  public static final String JSON_PROPERTY_ONE_MONTH_CORRELATION = "oneMonthCorrelation";
  @javax.annotation.Nullable
  private Float oneMonthCorrelation;

  public static final String JSON_PROPERTY_ONE_YEAR_CORRELATION = "oneYearCorrelation";
  @javax.annotation.Nullable
  private Float oneYearCorrelation;

  public static final String JSON_PROPERTY_SIX_MONTH_CORRELATION = "sixMonthCorrelation";
  @javax.annotation.Nullable
  private Float sixMonthCorrelation;

  public static final String JSON_PROPERTY_THREE_MONTH_CORRELATION = "threeMonthCorrelation";
  @javax.annotation.Nullable
  private Float threeMonthCorrelation;

  public static final String JSON_PROPERTY_TWO_WEEK_CORRELATION = "twoWeekCorrelation";
  @javax.annotation.Nullable
  private Float twoWeekCorrelation;

  public static final String JSON_PROPERTY_TWO_YEAR_CORRELATION = "twoYearCorrelation";
  @javax.annotation.Nullable
  private Float twoYearCorrelation;

  public KeyCustomersSuppliers() {
  }

  public KeyCustomersSuppliers symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Symbol
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public KeyCustomersSuppliers name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public KeyCustomersSuppliers country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Country
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public KeyCustomersSuppliers industry(@javax.annotation.Nullable String industry) {
    
    this.industry = industry;
    return this;
  }

  /**
   * Industry
   * @return industry
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIndustry() {
    return industry;
  }


  @JsonProperty(JSON_PROPERTY_INDUSTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIndustry(@javax.annotation.Nullable String industry) {
    this.industry = industry;
  }

  public KeyCustomersSuppliers customer(@javax.annotation.Nullable Boolean customer) {
    
    this.customer = customer;
    return this;
  }

  /**
   * Whether the company is a customer.
   * @return customer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCustomer() {
    return customer;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomer(@javax.annotation.Nullable Boolean customer) {
    this.customer = customer;
  }

  public KeyCustomersSuppliers supplier(@javax.annotation.Nullable Boolean supplier) {
    
    this.supplier = supplier;
    return this;
  }

  /**
   * Whether the company is a supplier
   * @return supplier
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSupplier() {
    return supplier;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplier(@javax.annotation.Nullable Boolean supplier) {
    this.supplier = supplier;
  }

  public KeyCustomersSuppliers oneMonthCorrelation(@javax.annotation.Nullable Float oneMonthCorrelation) {
    
    this.oneMonthCorrelation = oneMonthCorrelation;
    return this;
  }

  /**
   * 1-month price correlation
   * @return oneMonthCorrelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ONE_MONTH_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getOneMonthCorrelation() {
    return oneMonthCorrelation;
  }


  @JsonProperty(JSON_PROPERTY_ONE_MONTH_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOneMonthCorrelation(@javax.annotation.Nullable Float oneMonthCorrelation) {
    this.oneMonthCorrelation = oneMonthCorrelation;
  }

  public KeyCustomersSuppliers oneYearCorrelation(@javax.annotation.Nullable Float oneYearCorrelation) {
    
    this.oneYearCorrelation = oneYearCorrelation;
    return this;
  }

  /**
   * 1-year price correlation
   * @return oneYearCorrelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ONE_YEAR_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getOneYearCorrelation() {
    return oneYearCorrelation;
  }


  @JsonProperty(JSON_PROPERTY_ONE_YEAR_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOneYearCorrelation(@javax.annotation.Nullable Float oneYearCorrelation) {
    this.oneYearCorrelation = oneYearCorrelation;
  }

  public KeyCustomersSuppliers sixMonthCorrelation(@javax.annotation.Nullable Float sixMonthCorrelation) {
    
    this.sixMonthCorrelation = sixMonthCorrelation;
    return this;
  }

  /**
   * 6-month price correlation
   * @return sixMonthCorrelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SIX_MONTH_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getSixMonthCorrelation() {
    return sixMonthCorrelation;
  }


  @JsonProperty(JSON_PROPERTY_SIX_MONTH_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSixMonthCorrelation(@javax.annotation.Nullable Float sixMonthCorrelation) {
    this.sixMonthCorrelation = sixMonthCorrelation;
  }

  public KeyCustomersSuppliers threeMonthCorrelation(@javax.annotation.Nullable Float threeMonthCorrelation) {
    
    this.threeMonthCorrelation = threeMonthCorrelation;
    return this;
  }

  /**
   * 3-month price correlation
   * @return threeMonthCorrelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THREE_MONTH_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getThreeMonthCorrelation() {
    return threeMonthCorrelation;
  }


  @JsonProperty(JSON_PROPERTY_THREE_MONTH_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThreeMonthCorrelation(@javax.annotation.Nullable Float threeMonthCorrelation) {
    this.threeMonthCorrelation = threeMonthCorrelation;
  }

  public KeyCustomersSuppliers twoWeekCorrelation(@javax.annotation.Nullable Float twoWeekCorrelation) {
    
    this.twoWeekCorrelation = twoWeekCorrelation;
    return this;
  }

  /**
   * 2-week price correlation
   * @return twoWeekCorrelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TWO_WEEK_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getTwoWeekCorrelation() {
    return twoWeekCorrelation;
  }


  @JsonProperty(JSON_PROPERTY_TWO_WEEK_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTwoWeekCorrelation(@javax.annotation.Nullable Float twoWeekCorrelation) {
    this.twoWeekCorrelation = twoWeekCorrelation;
  }

  public KeyCustomersSuppliers twoYearCorrelation(@javax.annotation.Nullable Float twoYearCorrelation) {
    
    this.twoYearCorrelation = twoYearCorrelation;
    return this;
  }

  /**
   * 2-year price correlation
   * @return twoYearCorrelation
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TWO_YEAR_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getTwoYearCorrelation() {
    return twoYearCorrelation;
  }


  @JsonProperty(JSON_PROPERTY_TWO_YEAR_CORRELATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTwoYearCorrelation(@javax.annotation.Nullable Float twoYearCorrelation) {
    this.twoYearCorrelation = twoYearCorrelation;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeyCustomersSuppliers keyCustomersSuppliers = (KeyCustomersSuppliers) o;
    return Objects.equals(this.symbol, keyCustomersSuppliers.symbol) &&
        Objects.equals(this.name, keyCustomersSuppliers.name) &&
        Objects.equals(this.country, keyCustomersSuppliers.country) &&
        Objects.equals(this.industry, keyCustomersSuppliers.industry) &&
        Objects.equals(this.customer, keyCustomersSuppliers.customer) &&
        Objects.equals(this.supplier, keyCustomersSuppliers.supplier) &&
        Objects.equals(this.oneMonthCorrelation, keyCustomersSuppliers.oneMonthCorrelation) &&
        Objects.equals(this.oneYearCorrelation, keyCustomersSuppliers.oneYearCorrelation) &&
        Objects.equals(this.sixMonthCorrelation, keyCustomersSuppliers.sixMonthCorrelation) &&
        Objects.equals(this.threeMonthCorrelation, keyCustomersSuppliers.threeMonthCorrelation) &&
        Objects.equals(this.twoWeekCorrelation, keyCustomersSuppliers.twoWeekCorrelation) &&
        Objects.equals(this.twoYearCorrelation, keyCustomersSuppliers.twoYearCorrelation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, name, country, industry, customer, supplier, oneMonthCorrelation, oneYearCorrelation, sixMonthCorrelation, threeMonthCorrelation, twoWeekCorrelation, twoYearCorrelation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyCustomersSuppliers {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    industry: ").append(toIndentedString(industry)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    supplier: ").append(toIndentedString(supplier)).append("\n");
    sb.append("    oneMonthCorrelation: ").append(toIndentedString(oneMonthCorrelation)).append("\n");
    sb.append("    oneYearCorrelation: ").append(toIndentedString(oneYearCorrelation)).append("\n");
    sb.append("    sixMonthCorrelation: ").append(toIndentedString(sixMonthCorrelation)).append("\n");
    sb.append("    threeMonthCorrelation: ").append(toIndentedString(threeMonthCorrelation)).append("\n");
    sb.append("    twoWeekCorrelation: ").append(toIndentedString(twoWeekCorrelation)).append("\n");
    sb.append("    twoYearCorrelation: ").append(toIndentedString(twoYearCorrelation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

