/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * LobbyingData
 */
@JsonPropertyOrder({
  LobbyingData.JSON_PROPERTY_SYMBOL,
  LobbyingData.JSON_PROPERTY_NAME,
  LobbyingData.JSON_PROPERTY_DESCRIPTION,
  LobbyingData.JSON_PROPERTY_COUNTRY,
  LobbyingData.JSON_PROPERTY_YEAR,
  LobbyingData.JSON_PROPERTY_PERIOD,
  LobbyingData.JSON_PROPERTY_INCOME,
  LobbyingData.JSON_PROPERTY_EXPENSES,
  LobbyingData.JSON_PROPERTY_DOCUMENT_URL,
  LobbyingData.JSON_PROPERTY_POSTED_NAME,
  LobbyingData.JSON_PROPERTY_DATE,
  LobbyingData.JSON_PROPERTY_CLIENT_ID,
  LobbyingData.JSON_PROPERTY_REGISTRANT_ID,
  LobbyingData.JSON_PROPERTY_SENATE_ID,
  LobbyingData.JSON_PROPERTY_HOUSEREGISTRANT_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class LobbyingData {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  @javax.annotation.Nullable
  private String country;

  public static final String JSON_PROPERTY_YEAR = "year";
  @javax.annotation.Nullable
  private Long year;

  public static final String JSON_PROPERTY_PERIOD = "period";
  @javax.annotation.Nullable
  private String period;

  public static final String JSON_PROPERTY_INCOME = "income";
  @javax.annotation.Nullable
  private Float income;

  public static final String JSON_PROPERTY_EXPENSES = "expenses";
  @javax.annotation.Nullable
  private Float expenses;

  public static final String JSON_PROPERTY_DOCUMENT_URL = "documentUrl";
  @javax.annotation.Nullable
  private String documentUrl;

  public static final String JSON_PROPERTY_POSTED_NAME = "postedName";
  @javax.annotation.Nullable
  private String postedName;

  public static final String JSON_PROPERTY_DATE = "date";
  @javax.annotation.Nullable
  private String date;

  public static final String JSON_PROPERTY_CLIENT_ID = "clientId";
  @javax.annotation.Nullable
  private String clientId;

  public static final String JSON_PROPERTY_REGISTRANT_ID = "registrantId";
  @javax.annotation.Nullable
  private String registrantId;

  public static final String JSON_PROPERTY_SENATE_ID = "senateId";
  @javax.annotation.Nullable
  private String senateId;

  public static final String JSON_PROPERTY_HOUSEREGISTRANT_ID = "houseregistrantId";
  @javax.annotation.Nullable
  private String houseregistrantId;

  public LobbyingData() {
  }

  public LobbyingData symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Symbol.
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public LobbyingData name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Company&#39;s name.
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }

  public LobbyingData description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Description.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public LobbyingData country(@javax.annotation.Nullable String country) {
    
    this.country = country;
    return this;
  }

  /**
   * Country.
   * @return country
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(@javax.annotation.Nullable String country) {
    this.country = country;
  }

  public LobbyingData year(@javax.annotation.Nullable Long year) {
    
    this.year = year;
    return this;
  }

  /**
   * Year.
   * @return year
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getYear() {
    return year;
  }


  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYear(@javax.annotation.Nullable Long year) {
    this.year = year;
  }

  public LobbyingData period(@javax.annotation.Nullable String period) {
    
    this.period = period;
    return this;
  }

  /**
   * Period.
   * @return period
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPeriod() {
    return period;
  }


  @JsonProperty(JSON_PROPERTY_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriod(@javax.annotation.Nullable String period) {
    this.period = period;
  }

  public LobbyingData income(@javax.annotation.Nullable Float income) {
    
    this.income = income;
    return this;
  }

  /**
   * Income reported by lobbying firms.
   * @return income
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getIncome() {
    return income;
  }


  @JsonProperty(JSON_PROPERTY_INCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncome(@javax.annotation.Nullable Float income) {
    this.income = income;
  }

  public LobbyingData expenses(@javax.annotation.Nullable Float expenses) {
    
    this.expenses = expenses;
    return this;
  }

  /**
   * Expenses reported by the company.
   * @return expenses
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPENSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getExpenses() {
    return expenses;
  }


  @JsonProperty(JSON_PROPERTY_EXPENSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpenses(@javax.annotation.Nullable Float expenses) {
    this.expenses = expenses;
  }

  public LobbyingData documentUrl(@javax.annotation.Nullable String documentUrl) {
    
    this.documentUrl = documentUrl;
    return this;
  }

  /**
   * Document&#39;s URL.
   * @return documentUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentUrl() {
    return documentUrl;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentUrl(@javax.annotation.Nullable String documentUrl) {
    this.documentUrl = documentUrl;
  }

  public LobbyingData postedName(@javax.annotation.Nullable String postedName) {
    
    this.postedName = postedName;
    return this;
  }

  /**
   * Posted name.
   * @return postedName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTED_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostedName() {
    return postedName;
  }


  @JsonProperty(JSON_PROPERTY_POSTED_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostedName(@javax.annotation.Nullable String postedName) {
    this.postedName = postedName;
  }

  public LobbyingData date(@javax.annotation.Nullable String date) {
    
    this.date = date;
    return this;
  }

  /**
   * Date.
   * @return date
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDate() {
    return date;
  }


  @JsonProperty(JSON_PROPERTY_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDate(@javax.annotation.Nullable String date) {
    this.date = date;
  }

  public LobbyingData clientId(@javax.annotation.Nullable String clientId) {
    
    this.clientId = clientId;
    return this;
  }

  /**
   * Client ID.
   * @return clientId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getClientId() {
    return clientId;
  }


  @JsonProperty(JSON_PROPERTY_CLIENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setClientId(@javax.annotation.Nullable String clientId) {
    this.clientId = clientId;
  }

  public LobbyingData registrantId(@javax.annotation.Nullable String registrantId) {
    
    this.registrantId = registrantId;
    return this;
  }

  /**
   * Registrant ID.
   * @return registrantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REGISTRANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRegistrantId() {
    return registrantId;
  }


  @JsonProperty(JSON_PROPERTY_REGISTRANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegistrantId(@javax.annotation.Nullable String registrantId) {
    this.registrantId = registrantId;
  }

  public LobbyingData senateId(@javax.annotation.Nullable String senateId) {
    
    this.senateId = senateId;
    return this;
  }

  /**
   * Senate ID.
   * @return senateId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSenateId() {
    return senateId;
  }


  @JsonProperty(JSON_PROPERTY_SENATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenateId(@javax.annotation.Nullable String senateId) {
    this.senateId = senateId;
  }

  public LobbyingData houseregistrantId(@javax.annotation.Nullable String houseregistrantId) {
    
    this.houseregistrantId = houseregistrantId;
    return this;
  }

  /**
   * House registrant ID.
   * @return houseregistrantId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HOUSEREGISTRANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHouseregistrantId() {
    return houseregistrantId;
  }


  @JsonProperty(JSON_PROPERTY_HOUSEREGISTRANT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHouseregistrantId(@javax.annotation.Nullable String houseregistrantId) {
    this.houseregistrantId = houseregistrantId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LobbyingData lobbyingData = (LobbyingData) o;
    return Objects.equals(this.symbol, lobbyingData.symbol) &&
        Objects.equals(this.name, lobbyingData.name) &&
        Objects.equals(this.description, lobbyingData.description) &&
        Objects.equals(this.country, lobbyingData.country) &&
        Objects.equals(this.year, lobbyingData.year) &&
        Objects.equals(this.period, lobbyingData.period) &&
        Objects.equals(this.income, lobbyingData.income) &&
        Objects.equals(this.expenses, lobbyingData.expenses) &&
        Objects.equals(this.documentUrl, lobbyingData.documentUrl) &&
        Objects.equals(this.postedName, lobbyingData.postedName) &&
        Objects.equals(this.date, lobbyingData.date) &&
        Objects.equals(this.clientId, lobbyingData.clientId) &&
        Objects.equals(this.registrantId, lobbyingData.registrantId) &&
        Objects.equals(this.senateId, lobbyingData.senateId) &&
        Objects.equals(this.houseregistrantId, lobbyingData.houseregistrantId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, name, description, country, year, period, income, expenses, documentUrl, postedName, date, clientId, registrantId, senateId, houseregistrantId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LobbyingData {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    income: ").append(toIndentedString(income)).append("\n");
    sb.append("    expenses: ").append(toIndentedString(expenses)).append("\n");
    sb.append("    documentUrl: ").append(toIndentedString(documentUrl)).append("\n");
    sb.append("    postedName: ").append(toIndentedString(postedName)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    clientId: ").append(toIndentedString(clientId)).append("\n");
    sb.append("    registrantId: ").append(toIndentedString(registrantId)).append("\n");
    sb.append("    senateId: ").append(toIndentedString(senateId)).append("\n");
    sb.append("    houseregistrantId: ").append(toIndentedString(houseregistrantId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

