/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.openapitools.client.model.CompanyNewsStatistics;
import org.openapitools.client.model.Sentiment;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * NewsSentiment
 */
@JsonPropertyOrder({
  NewsSentiment.JSON_PROPERTY_BUZZ,
  NewsSentiment.JSON_PROPERTY_COMPANY_NEWS_SCORE,
  NewsSentiment.JSON_PROPERTY_SECTOR_AVERAGE_BULLISH_PERCENT,
  NewsSentiment.JSON_PROPERTY_SECTOR_AVERAGE_NEWS_SCORE,
  NewsSentiment.JSON_PROPERTY_SENTIMENT,
  NewsSentiment.JSON_PROPERTY_SYMBOL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class NewsSentiment {
  public static final String JSON_PROPERTY_BUZZ = "buzz";
  @javax.annotation.Nullable
  private CompanyNewsStatistics buzz;

  public static final String JSON_PROPERTY_COMPANY_NEWS_SCORE = "companyNewsScore";
  @javax.annotation.Nullable
  private Float companyNewsScore;

  public static final String JSON_PROPERTY_SECTOR_AVERAGE_BULLISH_PERCENT = "sectorAverageBullishPercent";
  @javax.annotation.Nullable
  private Float sectorAverageBullishPercent;

  public static final String JSON_PROPERTY_SECTOR_AVERAGE_NEWS_SCORE = "sectorAverageNewsScore";
  @javax.annotation.Nullable
  private Float sectorAverageNewsScore;

  public static final String JSON_PROPERTY_SENTIMENT = "sentiment";
  @javax.annotation.Nullable
  private Sentiment sentiment;

  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public NewsSentiment() {
  }

  public NewsSentiment buzz(@javax.annotation.Nullable CompanyNewsStatistics buzz) {
    
    this.buzz = buzz;
    return this;
  }

  /**
   * Get buzz
   * @return buzz
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUZZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CompanyNewsStatistics getBuzz() {
    return buzz;
  }


  @JsonProperty(JSON_PROPERTY_BUZZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuzz(@javax.annotation.Nullable CompanyNewsStatistics buzz) {
    this.buzz = buzz;
  }

  public NewsSentiment companyNewsScore(@javax.annotation.Nullable Float companyNewsScore) {
    
    this.companyNewsScore = companyNewsScore;
    return this;
  }

  /**
   * News score.
   * @return companyNewsScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY_NEWS_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getCompanyNewsScore() {
    return companyNewsScore;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_NEWS_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyNewsScore(@javax.annotation.Nullable Float companyNewsScore) {
    this.companyNewsScore = companyNewsScore;
  }

  public NewsSentiment sectorAverageBullishPercent(@javax.annotation.Nullable Float sectorAverageBullishPercent) {
    
    this.sectorAverageBullishPercent = sectorAverageBullishPercent;
    return this;
  }

  /**
   * Sector average bullish percent.
   * @return sectorAverageBullishPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTOR_AVERAGE_BULLISH_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getSectorAverageBullishPercent() {
    return sectorAverageBullishPercent;
  }


  @JsonProperty(JSON_PROPERTY_SECTOR_AVERAGE_BULLISH_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectorAverageBullishPercent(@javax.annotation.Nullable Float sectorAverageBullishPercent) {
    this.sectorAverageBullishPercent = sectorAverageBullishPercent;
  }

  public NewsSentiment sectorAverageNewsScore(@javax.annotation.Nullable Float sectorAverageNewsScore) {
    
    this.sectorAverageNewsScore = sectorAverageNewsScore;
    return this;
  }

  /**
   * Sectore average score.
   * @return sectorAverageNewsScore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SECTOR_AVERAGE_NEWS_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getSectorAverageNewsScore() {
    return sectorAverageNewsScore;
  }


  @JsonProperty(JSON_PROPERTY_SECTOR_AVERAGE_NEWS_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSectorAverageNewsScore(@javax.annotation.Nullable Float sectorAverageNewsScore) {
    this.sectorAverageNewsScore = sectorAverageNewsScore;
  }

  public NewsSentiment sentiment(@javax.annotation.Nullable Sentiment sentiment) {
    
    this.sentiment = sentiment;
    return this;
  }

  /**
   * Get sentiment
   * @return sentiment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SENTIMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Sentiment getSentiment() {
    return sentiment;
  }


  @JsonProperty(JSON_PROPERTY_SENTIMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSentiment(@javax.annotation.Nullable Sentiment sentiment) {
    this.sentiment = sentiment;
  }

  public NewsSentiment symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Requested symbol.
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewsSentiment newsSentiment = (NewsSentiment) o;
    return Objects.equals(this.buzz, newsSentiment.buzz) &&
        Objects.equals(this.companyNewsScore, newsSentiment.companyNewsScore) &&
        Objects.equals(this.sectorAverageBullishPercent, newsSentiment.sectorAverageBullishPercent) &&
        Objects.equals(this.sectorAverageNewsScore, newsSentiment.sectorAverageNewsScore) &&
        Objects.equals(this.sentiment, newsSentiment.sentiment) &&
        Objects.equals(this.symbol, newsSentiment.symbol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(buzz, companyNewsScore, sectorAverageBullishPercent, sectorAverageNewsScore, sentiment, symbol);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewsSentiment {\n");
    sb.append("    buzz: ").append(toIndentedString(buzz)).append("\n");
    sb.append("    companyNewsScore: ").append(toIndentedString(companyNewsScore)).append("\n");
    sb.append("    sectorAverageBullishPercent: ").append(toIndentedString(sectorAverageBullishPercent)).append("\n");
    sb.append("    sectorAverageNewsScore: ").append(toIndentedString(sectorAverageNewsScore)).append("\n");
    sb.append("    sentiment: ").append(toIndentedString(sentiment)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

