/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PresentationData
 */
@JsonPropertyOrder({
  PresentationData.JSON_PROPERTY_QUARTER,
  PresentationData.JSON_PROPERTY_YEAR,
  PresentationData.JSON_PROPERTY_URL,
  PresentationData.JSON_PROPERTY_TITLE,
  PresentationData.JSON_PROPERTY_AT_TIME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PresentationData {
  public static final String JSON_PROPERTY_QUARTER = "quarter";
  @javax.annotation.Nullable
  private Long quarter;

  public static final String JSON_PROPERTY_YEAR = "year";
  @javax.annotation.Nullable
  private Long year;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_AT_TIME = "atTime";
  @javax.annotation.Nullable
  private String atTime;

  public PresentationData() {
  }

  public PresentationData quarter(@javax.annotation.Nullable Long quarter) {
    
    this.quarter = quarter;
    return this;
  }

  /**
   * Quarter
   * @return quarter
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QUARTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getQuarter() {
    return quarter;
  }


  @JsonProperty(JSON_PROPERTY_QUARTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuarter(@javax.annotation.Nullable Long quarter) {
    this.quarter = quarter;
  }

  public PresentationData year(@javax.annotation.Nullable Long year) {
    
    this.year = year;
    return this;
  }

  /**
   * Year
   * @return year
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getYear() {
    return year;
  }


  @JsonProperty(JSON_PROPERTY_YEAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setYear(@javax.annotation.Nullable Long year) {
    this.year = year;
  }

  public PresentationData url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Presentation url
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }

  public PresentationData title(@javax.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Title
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }

  public PresentationData atTime(@javax.annotation.Nullable String atTime) {
    
    this.atTime = atTime;
    return this;
  }

  /**
   * At Time.
   * @return atTime
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAtTime() {
    return atTime;
  }


  @JsonProperty(JSON_PROPERTY_AT_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAtTime(@javax.annotation.Nullable String atTime) {
    this.atTime = atTime;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PresentationData presentationData = (PresentationData) o;
    return Objects.equals(this.quarter, presentationData.quarter) &&
        Objects.equals(this.year, presentationData.year) &&
        Objects.equals(this.url, presentationData.url) &&
        Objects.equals(this.title, presentationData.title) &&
        Objects.equals(this.atTime, presentationData.atTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quarter, year, url, title, atTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PresentationData {\n");
    sb.append("    quarter: ").append(toIndentedString(quarter)).append("\n");
    sb.append("    year: ").append(toIndentedString(year)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    atTime: ").append(toIndentedString(atTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

