/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SearchBody
 */
@JsonPropertyOrder({
  SearchBody.JSON_PROPERTY_QUERY,
  SearchBody.JSON_PROPERTY_ISINS,
  SearchBody.JSON_PROPERTY_CUSIPS,
  SearchBody.JSON_PROPERTY_CIKS,
  SearchBody.JSON_PROPERTY_SEDAR_IDS,
  SearchBody.JSON_PROPERTY_CH_IDS,
  SearchBody.JSON_PROPERTY_SYMBOLS,
  SearchBody.JSON_PROPERTY_SEDOLS,
  SearchBody.JSON_PROPERTY_SOURCES,
  SearchBody.JSON_PROPERTY_FORMS,
  SearchBody.JSON_PROPERTY_GICS,
  SearchBody.JSON_PROPERTY_NAICS,
  SearchBody.JSON_PROPERTY_EXHIBITS,
  SearchBody.JSON_PROPERTY_EXCHANGES,
  SearchBody.JSON_PROPERTY_COUNTRIES,
  SearchBody.JSON_PROPERTY_ACTS,
  SearchBody.JSON_PROPERTY_CAPS,
  SearchBody.JSON_PROPERTY_FROM_DATE,
  SearchBody.JSON_PROPERTY_TO_DATE,
  SearchBody.JSON_PROPERTY_PAGE,
  SearchBody.JSON_PROPERTY_SORT,
  SearchBody.JSON_PROPERTY_HIGHLIGHTED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SearchBody {
  public static final String JSON_PROPERTY_QUERY = "query";
  @javax.annotation.Nonnull
  private String query;

  public static final String JSON_PROPERTY_ISINS = "isins";
  @javax.annotation.Nullable
  private String isins;

  public static final String JSON_PROPERTY_CUSIPS = "cusips";
  @javax.annotation.Nullable
  private String cusips;

  public static final String JSON_PROPERTY_CIKS = "ciks";
  @javax.annotation.Nullable
  private String ciks;

  public static final String JSON_PROPERTY_SEDAR_IDS = "sedarIds";
  @javax.annotation.Nullable
  private String sedarIds;

  public static final String JSON_PROPERTY_CH_IDS = "chIds";
  @javax.annotation.Nullable
  private String chIds;

  public static final String JSON_PROPERTY_SYMBOLS = "symbols";
  @javax.annotation.Nullable
  private String symbols;

  public static final String JSON_PROPERTY_SEDOLS = "sedols";
  @javax.annotation.Nullable
  private String sedols;

  public static final String JSON_PROPERTY_SOURCES = "sources";
  @javax.annotation.Nullable
  private String sources;

  public static final String JSON_PROPERTY_FORMS = "forms";
  @javax.annotation.Nullable
  private String forms;

  public static final String JSON_PROPERTY_GICS = "gics";
  @javax.annotation.Nullable
  private String gics;

  public static final String JSON_PROPERTY_NAICS = "naics";
  @javax.annotation.Nullable
  private String naics;

  public static final String JSON_PROPERTY_EXHIBITS = "exhibits";
  @javax.annotation.Nullable
  private String exhibits;

  public static final String JSON_PROPERTY_EXCHANGES = "exchanges";
  @javax.annotation.Nullable
  private String exchanges;

  public static final String JSON_PROPERTY_COUNTRIES = "countries";
  @javax.annotation.Nullable
  private String countries;

  public static final String JSON_PROPERTY_ACTS = "acts";
  @javax.annotation.Nullable
  private String acts;

  public static final String JSON_PROPERTY_CAPS = "caps";
  @javax.annotation.Nullable
  private String caps;

  public static final String JSON_PROPERTY_FROM_DATE = "fromDate";
  @javax.annotation.Nullable
  private String fromDate;

  public static final String JSON_PROPERTY_TO_DATE = "toDate";
  @javax.annotation.Nullable
  private String toDate;

  public static final String JSON_PROPERTY_PAGE = "page";
  @javax.annotation.Nullable
  private String page;

  public static final String JSON_PROPERTY_SORT = "sort";
  @javax.annotation.Nullable
  private String sort;

  public static final String JSON_PROPERTY_HIGHLIGHTED = "highlighted";
  @javax.annotation.Nullable
  private Boolean highlighted;

  public SearchBody() {
  }

  public SearchBody query(@javax.annotation.Nonnull String query) {
    
    this.query = query;
    return this;
  }

  /**
   * Search query
   * @return query
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQuery() {
    return query;
  }


  @JsonProperty(JSON_PROPERTY_QUERY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuery(@javax.annotation.Nonnull String query) {
    this.query = query;
  }

  public SearchBody isins(@javax.annotation.Nullable String isins) {
    
    this.isins = isins;
    return this;
  }

  /**
   * List of isin to search, comma separated (Max: 50).
   * @return isins
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getIsins() {
    return isins;
  }


  @JsonProperty(JSON_PROPERTY_ISINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsins(@javax.annotation.Nullable String isins) {
    this.isins = isins;
  }

  public SearchBody cusips(@javax.annotation.Nullable String cusips) {
    
    this.cusips = cusips;
    return this;
  }

  /**
   * List of cusip to search, comma separated (Max: 50).
   * @return cusips
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CUSIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCusips() {
    return cusips;
  }


  @JsonProperty(JSON_PROPERTY_CUSIPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCusips(@javax.annotation.Nullable String cusips) {
    this.cusips = cusips;
  }

  public SearchBody ciks(@javax.annotation.Nullable String ciks) {
    
    this.ciks = ciks;
    return this;
  }

  /**
   * List of SEC Center Index Key to search, comma separated (Max: 50).
   * @return ciks
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CIKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCiks() {
    return ciks;
  }


  @JsonProperty(JSON_PROPERTY_CIKS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCiks(@javax.annotation.Nullable String ciks) {
    this.ciks = ciks;
  }

  public SearchBody sedarIds(@javax.annotation.Nullable String sedarIds) {
    
    this.sedarIds = sedarIds;
    return this;
  }

  /**
   * List of SEDAR issuer number to search, comma separated (Max: 50).
   * @return sedarIds
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEDAR_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSedarIds() {
    return sedarIds;
  }


  @JsonProperty(JSON_PROPERTY_SEDAR_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSedarIds(@javax.annotation.Nullable String sedarIds) {
    this.sedarIds = sedarIds;
  }

  public SearchBody chIds(@javax.annotation.Nullable String chIds) {
    
    this.chIds = chIds;
    return this;
  }

  /**
   * List of Companies House number to search, comma separated (Max: 50).
   * @return chIds
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CH_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getChIds() {
    return chIds;
  }


  @JsonProperty(JSON_PROPERTY_CH_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChIds(@javax.annotation.Nullable String chIds) {
    this.chIds = chIds;
  }

  public SearchBody symbols(@javax.annotation.Nullable String symbols) {
    
    this.symbols = symbols;
    return this;
  }

  /**
   * List of symbols to search, comma separated (Max: 50).
   * @return symbols
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbols() {
    return symbols;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbols(@javax.annotation.Nullable String symbols) {
    this.symbols = symbols;
  }

  public SearchBody sedols(@javax.annotation.Nullable String sedols) {
    
    this.sedols = sedols;
    return this;
  }

  /**
   * List of sedols to search, comma separated (Max: 50).
   * @return sedols
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEDOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSedols() {
    return sedols;
  }


  @JsonProperty(JSON_PROPERTY_SEDOLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSedols(@javax.annotation.Nullable String sedols) {
    this.sedols = sedols;
  }

  public SearchBody sources(@javax.annotation.Nullable String sources) {
    
    this.sources = sources;
    return this;
  }

  /**
   * List of sources to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return sources
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSources() {
    return sources;
  }


  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSources(@javax.annotation.Nullable String sources) {
    this.sources = sources;
  }

  public SearchBody forms(@javax.annotation.Nullable String forms) {
    
    this.forms = forms;
    return this;
  }

  /**
   * List of forms to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return forms
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getForms() {
    return forms;
  }


  @JsonProperty(JSON_PROPERTY_FORMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setForms(@javax.annotation.Nullable String forms) {
    this.forms = forms;
  }

  public SearchBody gics(@javax.annotation.Nullable String gics) {
    
    this.gics = gics;
    return this;
  }

  /**
   * List of gics to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return gics
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGics() {
    return gics;
  }


  @JsonProperty(JSON_PROPERTY_GICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGics(@javax.annotation.Nullable String gics) {
    this.gics = gics;
  }

  public SearchBody naics(@javax.annotation.Nullable String naics) {
    
    this.naics = naics;
    return this;
  }

  /**
   * List of sources to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return naics
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNaics() {
    return naics;
  }


  @JsonProperty(JSON_PROPERTY_NAICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNaics(@javax.annotation.Nullable String naics) {
    this.naics = naics;
  }

  public SearchBody exhibits(@javax.annotation.Nullable String exhibits) {
    
    this.exhibits = exhibits;
    return this;
  }

  /**
   * List of exhibits to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return exhibits
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXHIBITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExhibits() {
    return exhibits;
  }


  @JsonProperty(JSON_PROPERTY_EXHIBITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExhibits(@javax.annotation.Nullable String exhibits) {
    this.exhibits = exhibits;
  }

  public SearchBody exchanges(@javax.annotation.Nullable String exchanges) {
    
    this.exchanges = exchanges;
    return this;
  }

  /**
   * List of exchanges to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return exchanges
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExchanges() {
    return exchanges;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchanges(@javax.annotation.Nullable String exchanges) {
    this.exchanges = exchanges;
  }

  public SearchBody countries(@javax.annotation.Nullable String countries) {
    
    this.countries = countries;
    return this;
  }

  /**
   * List of sources to search, comma separated (Max: 50). Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return countries
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountries() {
    return countries;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountries(@javax.annotation.Nullable String countries) {
    this.countries = countries;
  }

  public SearchBody acts(@javax.annotation.Nullable String acts) {
    
    this.acts = acts;
    return this;
  }

  /**
   * List of SEC&#39;s exchanges act to search, comma separated. Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return acts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getActs() {
    return acts;
  }


  @JsonProperty(JSON_PROPERTY_ACTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActs(@javax.annotation.Nullable String acts) {
    this.acts = acts;
  }

  public SearchBody caps(@javax.annotation.Nullable String caps) {
    
    this.caps = caps;
    return this;
  }

  /**
   * List of market capitalization to search, comma separated. Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return caps
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CAPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCaps() {
    return caps;
  }


  @JsonProperty(JSON_PROPERTY_CAPS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCaps(@javax.annotation.Nullable String caps) {
    this.caps = caps;
  }

  public SearchBody fromDate(@javax.annotation.Nullable String fromDate) {
    
    this.fromDate = fromDate;
    return this;
  }

  /**
   * Search from date in format: YYYY-MM-DD, default from the last 2 years
   * @return fromDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFromDate() {
    return fromDate;
  }


  @JsonProperty(JSON_PROPERTY_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFromDate(@javax.annotation.Nullable String fromDate) {
    this.fromDate = fromDate;
  }

  public SearchBody toDate(@javax.annotation.Nullable String toDate) {
    
    this.toDate = toDate;
    return this;
  }

  /**
   * Search to date in format: YYYY-MM-DD, default to today
   * @return toDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getToDate() {
    return toDate;
  }


  @JsonProperty(JSON_PROPERTY_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setToDate(@javax.annotation.Nullable String toDate) {
    this.toDate = toDate;
  }

  public SearchBody page(@javax.annotation.Nullable String page) {
    
    this.page = page;
    return this;
  }

  /**
   * Use for pagination, default to page 1
   * @return page
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPage() {
    return page;
  }


  @JsonProperty(JSON_PROPERTY_PAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPage(@javax.annotation.Nullable String page) {
    this.page = page;
  }

  public SearchBody sort(@javax.annotation.Nullable String sort) {
    
    this.sort = sort;
    return this;
  }

  /**
   * Sort result by, default: sortMostRecent. Look at &lt;code&gt;/filter&lt;/code&gt; endpoint to see all available values.
   * @return sort
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSort() {
    return sort;
  }


  @JsonProperty(JSON_PROPERTY_SORT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSort(@javax.annotation.Nullable String sort) {
    this.sort = sort;
  }

  public SearchBody highlighted(@javax.annotation.Nullable Boolean highlighted) {
    
    this.highlighted = highlighted;
    return this;
  }

  /**
   * Enable highlight in returned filings. If enabled, only return 10 results each time
   * @return highlighted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HIGHLIGHTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHighlighted() {
    return highlighted;
  }


  @JsonProperty(JSON_PROPERTY_HIGHLIGHTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHighlighted(@javax.annotation.Nullable Boolean highlighted) {
    this.highlighted = highlighted;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchBody searchBody = (SearchBody) o;
    return Objects.equals(this.query, searchBody.query) &&
        Objects.equals(this.isins, searchBody.isins) &&
        Objects.equals(this.cusips, searchBody.cusips) &&
        Objects.equals(this.ciks, searchBody.ciks) &&
        Objects.equals(this.sedarIds, searchBody.sedarIds) &&
        Objects.equals(this.chIds, searchBody.chIds) &&
        Objects.equals(this.symbols, searchBody.symbols) &&
        Objects.equals(this.sedols, searchBody.sedols) &&
        Objects.equals(this.sources, searchBody.sources) &&
        Objects.equals(this.forms, searchBody.forms) &&
        Objects.equals(this.gics, searchBody.gics) &&
        Objects.equals(this.naics, searchBody.naics) &&
        Objects.equals(this.exhibits, searchBody.exhibits) &&
        Objects.equals(this.exchanges, searchBody.exchanges) &&
        Objects.equals(this.countries, searchBody.countries) &&
        Objects.equals(this.acts, searchBody.acts) &&
        Objects.equals(this.caps, searchBody.caps) &&
        Objects.equals(this.fromDate, searchBody.fromDate) &&
        Objects.equals(this.toDate, searchBody.toDate) &&
        Objects.equals(this.page, searchBody.page) &&
        Objects.equals(this.sort, searchBody.sort) &&
        Objects.equals(this.highlighted, searchBody.highlighted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(query, isins, cusips, ciks, sedarIds, chIds, symbols, sedols, sources, forms, gics, naics, exhibits, exchanges, countries, acts, caps, fromDate, toDate, page, sort, highlighted);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchBody {\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    isins: ").append(toIndentedString(isins)).append("\n");
    sb.append("    cusips: ").append(toIndentedString(cusips)).append("\n");
    sb.append("    ciks: ").append(toIndentedString(ciks)).append("\n");
    sb.append("    sedarIds: ").append(toIndentedString(sedarIds)).append("\n");
    sb.append("    chIds: ").append(toIndentedString(chIds)).append("\n");
    sb.append("    symbols: ").append(toIndentedString(symbols)).append("\n");
    sb.append("    sedols: ").append(toIndentedString(sedols)).append("\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("    forms: ").append(toIndentedString(forms)).append("\n");
    sb.append("    gics: ").append(toIndentedString(gics)).append("\n");
    sb.append("    naics: ").append(toIndentedString(naics)).append("\n");
    sb.append("    exhibits: ").append(toIndentedString(exhibits)).append("\n");
    sb.append("    exchanges: ").append(toIndentedString(exchanges)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    acts: ").append(toIndentedString(acts)).append("\n");
    sb.append("    caps: ").append(toIndentedString(caps)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    sort: ").append(toIndentedString(sort)).append("\n");
    sb.append("    highlighted: ").append(toIndentedString(highlighted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

