/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Sentiment
 */
@JsonPropertyOrder({
  Sentiment.JSON_PROPERTY_BEARISH_PERCENT,
  Sentiment.JSON_PROPERTY_BULLISH_PERCENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-07-29T21:39:04.016977118Z[Etc/UTC]", comments = "Generator version: 7.14.0")
public class Sentiment {
  public static final String JSON_PROPERTY_BEARISH_PERCENT = "bearishPercent";
  @javax.annotation.Nullable
  private Float bearishPercent;

  public static final String JSON_PROPERTY_BULLISH_PERCENT = "bullishPercent";
  @javax.annotation.Nullable
  private Float bullishPercent;

  public Sentiment() {
  }

  public Sentiment bearishPercent(@javax.annotation.Nullable Float bearishPercent) {
    
    this.bearishPercent = bearishPercent;
    return this;
  }

  /**
   * 
   * @return bearishPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BEARISH_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getBearishPercent() {
    return bearishPercent;
  }


  @JsonProperty(JSON_PROPERTY_BEARISH_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBearishPercent(@javax.annotation.Nullable Float bearishPercent) {
    this.bearishPercent = bearishPercent;
  }

  public Sentiment bullishPercent(@javax.annotation.Nullable Float bullishPercent) {
    
    this.bullishPercent = bullishPercent;
    return this;
  }

  /**
   * 
   * @return bullishPercent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BULLISH_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getBullishPercent() {
    return bullishPercent;
  }


  @JsonProperty(JSON_PROPERTY_BULLISH_PERCENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBullishPercent(@javax.annotation.Nullable Float bullishPercent) {
    this.bullishPercent = bullishPercent;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sentiment sentiment = (Sentiment) o;
    return Objects.equals(this.bearishPercent, sentiment.bearishPercent) &&
        Objects.equals(this.bullishPercent, sentiment.bullishPercent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bearishPercent, bullishPercent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sentiment {\n");
    sb.append("    bearishPercent: ").append(toIndentedString(bearishPercent)).append("\n");
    sb.append("    bullishPercent: ").append(toIndentedString(bullishPercent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

