/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * StockCandles
 */
@JsonPropertyOrder({
  StockCandles.JSON_PROPERTY_O,
  StockCandles.JSON_PROPERTY_H,
  StockCandles.JSON_PROPERTY_L,
  StockCandles.JSON_PROPERTY_C,
  StockCandles.JSON_PROPERTY_V,
  StockCandles.JSON_PROPERTY_T,
  StockCandles.JSON_PROPERTY_S
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class StockCandles {
  public static final String JSON_PROPERTY_O = "o";
  @javax.annotation.Nullable
  private List<Float> o = new ArrayList<>();

  public static final String JSON_PROPERTY_H = "h";
  @javax.annotation.Nullable
  private List<Float> h = new ArrayList<>();

  public static final String JSON_PROPERTY_L = "l";
  @javax.annotation.Nullable
  private List<Float> l = new ArrayList<>();

  public static final String JSON_PROPERTY_C = "c";
  @javax.annotation.Nullable
  private List<Float> c = new ArrayList<>();

  public static final String JSON_PROPERTY_V = "v";
  @javax.annotation.Nullable
  private List<Float> v = new ArrayList<>();

  public static final String JSON_PROPERTY_T = "t";
  @javax.annotation.Nullable
  private List<Long> t = new ArrayList<>();

  public static final String JSON_PROPERTY_S = "s";
  @javax.annotation.Nullable
  private String s;

  public StockCandles() {
  }

  public StockCandles o(@javax.annotation.Nullable List<Float> o) {
    
    this.o = o;
    return this;
  }

  public StockCandles addOItem(Float oItem) {
    if (this.o == null) {
      this.o = new ArrayList<>();
    }
    this.o.add(oItem);
    return this;
  }

  /**
   * List of open prices for returned candles.
   * @return o
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getO() {
    return o;
  }


  @JsonProperty(JSON_PROPERTY_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setO(@javax.annotation.Nullable List<Float> o) {
    this.o = o;
  }

  public StockCandles h(@javax.annotation.Nullable List<Float> h) {
    
    this.h = h;
    return this;
  }

  public StockCandles addHItem(Float hItem) {
    if (this.h == null) {
      this.h = new ArrayList<>();
    }
    this.h.add(hItem);
    return this;
  }

  /**
   * List of high prices for returned candles.
   * @return h
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getH() {
    return h;
  }


  @JsonProperty(JSON_PROPERTY_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setH(@javax.annotation.Nullable List<Float> h) {
    this.h = h;
  }

  public StockCandles l(@javax.annotation.Nullable List<Float> l) {
    
    this.l = l;
    return this;
  }

  public StockCandles addLItem(Float lItem) {
    if (this.l == null) {
      this.l = new ArrayList<>();
    }
    this.l.add(lItem);
    return this;
  }

  /**
   * List of low prices for returned candles.
   * @return l
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getL() {
    return l;
  }


  @JsonProperty(JSON_PROPERTY_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setL(@javax.annotation.Nullable List<Float> l) {
    this.l = l;
  }

  public StockCandles c(@javax.annotation.Nullable List<Float> c) {
    
    this.c = c;
    return this;
  }

  public StockCandles addCItem(Float cItem) {
    if (this.c == null) {
      this.c = new ArrayList<>();
    }
    this.c.add(cItem);
    return this;
  }

  /**
   * List of close prices for returned candles.
   * @return c
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getC() {
    return c;
  }


  @JsonProperty(JSON_PROPERTY_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setC(@javax.annotation.Nullable List<Float> c) {
    this.c = c;
  }

  public StockCandles v(@javax.annotation.Nullable List<Float> v) {
    
    this.v = v;
    return this;
  }

  public StockCandles addVItem(Float vItem) {
    if (this.v == null) {
      this.v = new ArrayList<>();
    }
    this.v.add(vItem);
    return this;
  }

  /**
   * List of volume data for returned candles.
   * @return v
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_V)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Float> getV() {
    return v;
  }


  @JsonProperty(JSON_PROPERTY_V)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setV(@javax.annotation.Nullable List<Float> v) {
    this.v = v;
  }

  public StockCandles t(@javax.annotation.Nullable List<Long> t) {
    
    this.t = t;
    return this;
  }

  public StockCandles addTItem(Long tItem) {
    if (this.t == null) {
      this.t = new ArrayList<>();
    }
    this.t.add(tItem);
    return this;
  }

  /**
   * List of timestamp for returned candles.
   * @return t
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Long> getT() {
    return t;
  }


  @JsonProperty(JSON_PROPERTY_T)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setT(@javax.annotation.Nullable List<Long> t) {
    this.t = t;
  }

  public StockCandles s(@javax.annotation.Nullable String s) {
    
    this.s = s;
    return this;
  }

  /**
   * Status of the response. This field can either be ok or no_data.
   * @return s
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getS() {
    return s;
  }


  @JsonProperty(JSON_PROPERTY_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setS(@javax.annotation.Nullable String s) {
    this.s = s;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StockCandles stockCandles = (StockCandles) o;
    return Objects.equals(this.o, stockCandles.o) &&
        Objects.equals(this.h, stockCandles.h) &&
        Objects.equals(this.l, stockCandles.l) &&
        Objects.equals(this.c, stockCandles.c) &&
        Objects.equals(this.v, stockCandles.v) &&
        Objects.equals(this.t, stockCandles.t) &&
        Objects.equals(this.s, stockCandles.s);
  }

  @Override
  public int hashCode() {
    return Objects.hash(o, h, l, c, v, t, s);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StockCandles {\n");
    sb.append("    o: ").append(toIndentedString(o)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    l: ").append(toIndentedString(l)).append("\n");
    sb.append("    c: ").append(toIndentedString(c)).append("\n");
    sb.append("    v: ").append(toIndentedString(v)).append("\n");
    sb.append("    t: ").append(toIndentedString(t)).append("\n");
    sb.append("    s: ").append(toIndentedString(s)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

