/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import bbb.finnhub.client.model.TechnicalAnalysis;
import bbb.finnhub.client.model.Trend;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AggregateIndicators
 */
@JsonPropertyOrder({
  AggregateIndicators.JSON_PROPERTY_TECHNICAL_ANALYSIS,
  AggregateIndicators.JSON_PROPERTY_TREND
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AggregateIndicators {
  public static final String JSON_PROPERTY_TECHNICAL_ANALYSIS = "technicalAnalysis";
  @javax.annotation.Nullable
  private TechnicalAnalysis technicalAnalysis;

  public static final String JSON_PROPERTY_TREND = "trend";
  @javax.annotation.Nullable
  private Trend trend;

  public AggregateIndicators() {
  }

  public AggregateIndicators technicalAnalysis(@javax.annotation.Nullable TechnicalAnalysis technicalAnalysis) {
    
    this.technicalAnalysis = technicalAnalysis;
    return this;
  }

  /**
   * Get technicalAnalysis
   * @return technicalAnalysis
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TECHNICAL_ANALYSIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public TechnicalAnalysis getTechnicalAnalysis() {
    return technicalAnalysis;
  }


  @JsonProperty(JSON_PROPERTY_TECHNICAL_ANALYSIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTechnicalAnalysis(@javax.annotation.Nullable TechnicalAnalysis technicalAnalysis) {
    this.technicalAnalysis = technicalAnalysis;
  }

  public AggregateIndicators trend(@javax.annotation.Nullable Trend trend) {
    
    this.trend = trend;
    return this;
  }

  /**
   * Get trend
   * @return trend
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TREND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Trend getTrend() {
    return trend;
  }


  @JsonProperty(JSON_PROPERTY_TREND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrend(@javax.annotation.Nullable Trend trend) {
    this.trend = trend;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregateIndicators aggregateIndicators = (AggregateIndicators) o;
    return Objects.equals(this.technicalAnalysis, aggregateIndicators.technicalAnalysis) &&
        Objects.equals(this.trend, aggregateIndicators.trend);
  }

  @Override
  public int hashCode() {
    return Objects.hash(technicalAnalysis, trend);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregateIndicators {\n");
    sb.append("    technicalAnalysis: ").append(toIndentedString(technicalAnalysis)).append("\n");
    sb.append("    trend: ").append(toIndentedString(trend)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

