/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import bbb.finnhub.client.model.CompanyEarningsQualityScoreData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CompanyEarningsQualityScore
 */
@JsonPropertyOrder({
  CompanyEarningsQualityScore.JSON_PROPERTY_SYMBOL,
  CompanyEarningsQualityScore.JSON_PROPERTY_FREQ,
  CompanyEarningsQualityScore.JSON_PROPERTY_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class CompanyEarningsQualityScore {
  public static final String JSON_PROPERTY_SYMBOL = "symbol";
  @javax.annotation.Nullable
  private String symbol;

  public static final String JSON_PROPERTY_FREQ = "freq";
  @javax.annotation.Nullable
  private String freq;

  public static final String JSON_PROPERTY_DATA = "data";
  @javax.annotation.Nullable
  private List<CompanyEarningsQualityScoreData> data = new ArrayList<>();

  public CompanyEarningsQualityScore() {
  }

  public CompanyEarningsQualityScore symbol(@javax.annotation.Nullable String symbol) {
    
    this.symbol = symbol;
    return this;
  }

  /**
   * Symbol
   * @return symbol
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSymbol() {
    return symbol;
  }


  @JsonProperty(JSON_PROPERTY_SYMBOL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSymbol(@javax.annotation.Nullable String symbol) {
    this.symbol = symbol;
  }

  public CompanyEarningsQualityScore freq(@javax.annotation.Nullable String freq) {
    
    this.freq = freq;
    return this;
  }

  /**
   * Frequency
   * @return freq
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FREQ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFreq() {
    return freq;
  }


  @JsonProperty(JSON_PROPERTY_FREQ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFreq(@javax.annotation.Nullable String freq) {
    this.freq = freq;
  }

  public CompanyEarningsQualityScore data(@javax.annotation.Nullable List<CompanyEarningsQualityScoreData> data) {
    
    this.data = data;
    return this;
  }

  public CompanyEarningsQualityScore addDataItem(CompanyEarningsQualityScoreData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<>();
    }
    this.data.add(dataItem);
    return this;
  }

  /**
   * Array of earnings quality score.
   * @return data
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CompanyEarningsQualityScoreData> getData() {
    return data;
  }


  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setData(@javax.annotation.Nullable List<CompanyEarningsQualityScoreData> data) {
    this.data = data;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompanyEarningsQualityScore companyEarningsQualityScore = (CompanyEarningsQualityScore) o;
    return Objects.equals(this.symbol, companyEarningsQualityScore.symbol) &&
        Objects.equals(this.freq, companyEarningsQualityScore.freq) &&
        Objects.equals(this.data, companyEarningsQualityScore.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, freq, data);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompanyEarningsQualityScore {\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    freq: ").append(toIndentedString(freq)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

