/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import bbb.finnhub.client.model.ExcerptResponse;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * DocumentResponse
 */
@JsonPropertyOrder({
  DocumentResponse.JSON_PROPERTY_DOCUMENT_ID,
  DocumentResponse.JSON_PROPERTY_TITLE,
  DocumentResponse.JSON_PROPERTY_HITS,
  DocumentResponse.JSON_PROPERTY_URL,
  DocumentResponse.JSON_PROPERTY_FORMAT,
  DocumentResponse.JSON_PROPERTY_EXCERPTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class DocumentResponse {
  public static final String JSON_PROPERTY_DOCUMENT_ID = "documentId";
  @javax.annotation.Nullable
  private String documentId;

  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  public static final String JSON_PROPERTY_HITS = "hits";
  @javax.annotation.Nullable
  private String hits;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_FORMAT = "format";
  @javax.annotation.Nullable
  private String format;

  public static final String JSON_PROPERTY_EXCERPTS = "excerpts";
  @javax.annotation.Nullable
  private List<ExcerptResponse> excerpts = new ArrayList<>();

  public DocumentResponse() {
  }

  public DocumentResponse documentId(@javax.annotation.Nullable String documentId) {
    
    this.documentId = documentId;
    return this;
  }

  /**
   * AlphaResearch internal document id.
   * @return documentId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentId() {
    return documentId;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentId(@javax.annotation.Nullable String documentId) {
    this.documentId = documentId;
  }

  public DocumentResponse title(@javax.annotation.Nullable String title) {
    
    this.title = title;
    return this;
  }

  /**
   * Title for this document.
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTitle() {
    return title;
  }


  @JsonProperty(JSON_PROPERTY_TITLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }

  public DocumentResponse hits(@javax.annotation.Nullable String hits) {
    
    this.hits = hits;
    return this;
  }

  /**
   * Number of hit in this document
   * @return hits
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_HITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getHits() {
    return hits;
  }


  @JsonProperty(JSON_PROPERTY_HITS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHits(@javax.annotation.Nullable String hits) {
    this.hits = hits;
  }

  public DocumentResponse url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Link to render this document
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }

  public DocumentResponse format(@javax.annotation.Nullable String format) {
    
    this.format = format;
    return this;
  }

  /**
   * Format of this document (can be html or pdf)
   * @return format
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFormat(@javax.annotation.Nullable String format) {
    this.format = format;
  }

  public DocumentResponse excerpts(@javax.annotation.Nullable List<ExcerptResponse> excerpts) {
    
    this.excerpts = excerpts;
    return this;
  }

  public DocumentResponse addExcerptsItem(ExcerptResponse excerptsItem) {
    if (this.excerpts == null) {
      this.excerpts = new ArrayList<>();
    }
    this.excerpts.add(excerptsItem);
    return this;
  }

  /**
   * Highlighted excerpts for this document
   * @return excerpts
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCERPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ExcerptResponse> getExcerpts() {
    return excerpts;
  }


  @JsonProperty(JSON_PROPERTY_EXCERPTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExcerpts(@javax.annotation.Nullable List<ExcerptResponse> excerpts) {
    this.excerpts = excerpts;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentResponse documentResponse = (DocumentResponse) o;
    return Objects.equals(this.documentId, documentResponse.documentId) &&
        Objects.equals(this.title, documentResponse.title) &&
        Objects.equals(this.hits, documentResponse.hits) &&
        Objects.equals(this.url, documentResponse.url) &&
        Objects.equals(this.format, documentResponse.format) &&
        Objects.equals(this.excerpts, documentResponse.excerpts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, title, hits, url, format, excerpts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentResponse {\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    hits: ").append(toIndentedString(hits)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    excerpts: ").append(toIndentedString(excerpts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

