/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * MarketCapData
 */
@JsonPropertyOrder({
  MarketCapData.JSON_PROPERTY_AT_DATE,
  MarketCapData.JSON_PROPERTY_MARKET_CAPITALIZATION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class MarketCapData {
  public static final String JSON_PROPERTY_AT_DATE = "atDate";
  @javax.annotation.Nullable
  private String atDate;

  public static final String JSON_PROPERTY_MARKET_CAPITALIZATION = "marketCapitalization";
  @javax.annotation.Nullable
  private Float marketCapitalization;

  public MarketCapData() {
  }

  public MarketCapData atDate(@javax.annotation.Nullable String atDate) {
    
    this.atDate = atDate;
    return this;
  }

  /**
   * Date of the reading
   * @return atDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAtDate() {
    return atDate;
  }


  @JsonProperty(JSON_PROPERTY_AT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAtDate(@javax.annotation.Nullable String atDate) {
    this.atDate = atDate;
  }

  public MarketCapData marketCapitalization(@javax.annotation.Nullable Float marketCapitalization) {
    
    this.marketCapitalization = marketCapitalization;
    return this;
  }

  /**
   * Value
   * @return marketCapitalization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MARKET_CAPITALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMarketCapitalization() {
    return marketCapitalization;
  }


  @JsonProperty(JSON_PROPERTY_MARKET_CAPITALIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMarketCapitalization(@javax.annotation.Nullable Float marketCapitalization) {
    this.marketCapitalization = marketCapitalization;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MarketCapData marketCapData = (MarketCapData) o;
    return Objects.equals(this.atDate, marketCapData.atDate) &&
        Objects.equals(this.marketCapitalization, marketCapData.marketCapitalization);
  }

  @Override
  public int hashCode() {
    return Objects.hash(atDate, marketCapitalization);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MarketCapData {\n");
    sb.append("    atDate: ").append(toIndentedString(atDate)).append("\n");
    sb.append("    marketCapitalization: ").append(toIndentedString(marketCapitalization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

