/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Quote
 */
@JsonPropertyOrder({
  Quote.JSON_PROPERTY_O,
  Quote.JSON_PROPERTY_H,
  Quote.JSON_PROPERTY_L,
  Quote.JSON_PROPERTY_C,
  Quote.JSON_PROPERTY_PC,
  Quote.JSON_PROPERTY_D,
  Quote.JSON_PROPERTY_DP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class Quote {
  public static final String JSON_PROPERTY_O = "o";
  @javax.annotation.Nullable
  private Float o;

  public static final String JSON_PROPERTY_H = "h";
  @javax.annotation.Nullable
  private Float h;

  public static final String JSON_PROPERTY_L = "l";
  @javax.annotation.Nullable
  private Float l;

  public static final String JSON_PROPERTY_C = "c";
  @javax.annotation.Nullable
  private Float c;

  public static final String JSON_PROPERTY_PC = "pc";
  @javax.annotation.Nullable
  private Float pc;

  public static final String JSON_PROPERTY_D = "d";
  @javax.annotation.Nullable
  private Float d;

  public static final String JSON_PROPERTY_DP = "dp";
  @javax.annotation.Nullable
  private Float dp;

  public Quote() {
  }

  public Quote o(@javax.annotation.Nullable Float o) {
    
    this.o = o;
    return this;
  }

  /**
   * Open price of the day
   * @return o
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getO() {
    return o;
  }


  @JsonProperty(JSON_PROPERTY_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setO(@javax.annotation.Nullable Float o) {
    this.o = o;
  }

  public Quote h(@javax.annotation.Nullable Float h) {
    
    this.h = h;
    return this;
  }

  /**
   * High price of the day
   * @return h
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getH() {
    return h;
  }


  @JsonProperty(JSON_PROPERTY_H)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setH(@javax.annotation.Nullable Float h) {
    this.h = h;
  }

  public Quote l(@javax.annotation.Nullable Float l) {
    
    this.l = l;
    return this;
  }

  /**
   * Low price of the day
   * @return l
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getL() {
    return l;
  }


  @JsonProperty(JSON_PROPERTY_L)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setL(@javax.annotation.Nullable Float l) {
    this.l = l;
  }

  public Quote c(@javax.annotation.Nullable Float c) {
    
    this.c = c;
    return this;
  }

  /**
   * Current price
   * @return c
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getC() {
    return c;
  }


  @JsonProperty(JSON_PROPERTY_C)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setC(@javax.annotation.Nullable Float c) {
    this.c = c;
  }

  public Quote pc(@javax.annotation.Nullable Float pc) {
    
    this.pc = pc;
    return this;
  }

  /**
   * Previous close price
   * @return pc
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getPc() {
    return pc;
  }


  @JsonProperty(JSON_PROPERTY_PC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPc(@javax.annotation.Nullable Float pc) {
    this.pc = pc;
  }

  public Quote d(@javax.annotation.Nullable Float d) {
    
    this.d = d;
    return this;
  }

  /**
   * Change
   * @return d
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getD() {
    return d;
  }


  @JsonProperty(JSON_PROPERTY_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setD(@javax.annotation.Nullable Float d) {
    this.d = d;
  }

  public Quote dp(@javax.annotation.Nullable Float dp) {
    
    this.dp = dp;
    return this;
  }

  /**
   * Percent change
   * @return dp
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getDp() {
    return dp;
  }


  @JsonProperty(JSON_PROPERTY_DP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDp(@javax.annotation.Nullable Float dp) {
    this.dp = dp;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Quote quote = (Quote) o;
    return Objects.equals(this.o, quote.o) &&
        Objects.equals(this.h, quote.h) &&
        Objects.equals(this.l, quote.l) &&
        Objects.equals(this.c, quote.c) &&
        Objects.equals(this.pc, quote.pc) &&
        Objects.equals(this.d, quote.d) &&
        Objects.equals(this.dp, quote.dp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(o, h, l, c, pc, d, dp);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Quote {\n");
    sb.append("    o: ").append(toIndentedString(o)).append("\n");
    sb.append("    h: ").append(toIndentedString(h)).append("\n");
    sb.append("    l: ").append(toIndentedString(l)).append("\n");
    sb.append("    c: ").append(toIndentedString(c)).append("\n");
    sb.append("    pc: ").append(toIndentedString(pc)).append("\n");
    sb.append("    d: ").append(toIndentedString(d)).append("\n");
    sb.append("    dp: ").append(toIndentedString(dp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

