/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UsptoPatent
 */
@JsonPropertyOrder({
  UsptoPatent.JSON_PROPERTY_APPLICATION_NUMBER,
  UsptoPatent.JSON_PROPERTY_COMPANY_FILING_NAME,
  UsptoPatent.JSON_PROPERTY_FILING_DATE,
  UsptoPatent.JSON_PROPERTY_DESCRIPTION,
  UsptoPatent.JSON_PROPERTY_FILING_STATUS,
  UsptoPatent.JSON_PROPERTY_PATENT_NUMBER,
  UsptoPatent.JSON_PROPERTY_PUBLICATION_DATE,
  UsptoPatent.JSON_PROPERTY_PATENT_TYPE,
  UsptoPatent.JSON_PROPERTY_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UsptoPatent {
  public static final String JSON_PROPERTY_APPLICATION_NUMBER = "applicationNumber";
  @javax.annotation.Nullable
  private String applicationNumber;

  public static final String JSON_PROPERTY_COMPANY_FILING_NAME = "companyFilingName";
  @javax.annotation.Nullable
  private List<String> companyFilingName = new ArrayList<>();

  public static final String JSON_PROPERTY_FILING_DATE = "filingDate";
  @javax.annotation.Nullable
  private String filingDate;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_FILING_STATUS = "filingStatus";
  @javax.annotation.Nullable
  private String filingStatus;

  public static final String JSON_PROPERTY_PATENT_NUMBER = "patentNumber";
  @javax.annotation.Nullable
  private String patentNumber;

  public static final String JSON_PROPERTY_PUBLICATION_DATE = "publicationDate";
  @javax.annotation.Nullable
  private String publicationDate;

  public static final String JSON_PROPERTY_PATENT_TYPE = "patentType";
  @javax.annotation.Nullable
  private String patentType;

  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public UsptoPatent() {
  }

  public UsptoPatent applicationNumber(@javax.annotation.Nullable String applicationNumber) {
    
    this.applicationNumber = applicationNumber;
    return this;
  }

  /**
   * Application Number.
   * @return applicationNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPLICATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getApplicationNumber() {
    return applicationNumber;
  }


  @JsonProperty(JSON_PROPERTY_APPLICATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplicationNumber(@javax.annotation.Nullable String applicationNumber) {
    this.applicationNumber = applicationNumber;
  }

  public UsptoPatent companyFilingName(@javax.annotation.Nullable List<String> companyFilingName) {
    
    this.companyFilingName = companyFilingName;
    return this;
  }

  public UsptoPatent addCompanyFilingNameItem(String companyFilingNameItem) {
    if (this.companyFilingName == null) {
      this.companyFilingName = new ArrayList<>();
    }
    this.companyFilingName.add(companyFilingNameItem);
    return this;
  }

  /**
   * Array of companies&#39; name on the patent.
   * @return companyFilingName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPANY_FILING_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getCompanyFilingName() {
    return companyFilingName;
  }


  @JsonProperty(JSON_PROPERTY_COMPANY_FILING_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompanyFilingName(@javax.annotation.Nullable List<String> companyFilingName) {
    this.companyFilingName = companyFilingName;
  }

  public UsptoPatent filingDate(@javax.annotation.Nullable String filingDate) {
    
    this.filingDate = filingDate;
    return this;
  }

  /**
   * Filing date.
   * @return filingDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilingDate() {
    return filingDate;
  }


  @JsonProperty(JSON_PROPERTY_FILING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilingDate(@javax.annotation.Nullable String filingDate) {
    this.filingDate = filingDate;
  }

  public UsptoPatent description(@javax.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Description.
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }

  public UsptoPatent filingStatus(@javax.annotation.Nullable String filingStatus) {
    
    this.filingStatus = filingStatus;
    return this;
  }

  /**
   * Filing status.
   * @return filingStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFilingStatus() {
    return filingStatus;
  }


  @JsonProperty(JSON_PROPERTY_FILING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilingStatus(@javax.annotation.Nullable String filingStatus) {
    this.filingStatus = filingStatus;
  }

  public UsptoPatent patentNumber(@javax.annotation.Nullable String patentNumber) {
    
    this.patentNumber = patentNumber;
    return this;
  }

  /**
   * Patent number.
   * @return patentNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATENT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPatentNumber() {
    return patentNumber;
  }


  @JsonProperty(JSON_PROPERTY_PATENT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPatentNumber(@javax.annotation.Nullable String patentNumber) {
    this.patentNumber = patentNumber;
  }

  public UsptoPatent publicationDate(@javax.annotation.Nullable String publicationDate) {
    
    this.publicationDate = publicationDate;
    return this;
  }

  /**
   * Publication date.
   * @return publicationDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLICATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPublicationDate() {
    return publicationDate;
  }


  @JsonProperty(JSON_PROPERTY_PUBLICATION_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublicationDate(@javax.annotation.Nullable String publicationDate) {
    this.publicationDate = publicationDate;
  }

  public UsptoPatent patentType(@javax.annotation.Nullable String patentType) {
    
    this.patentType = patentType;
    return this;
  }

  /**
   * Patent&#39;s type.
   * @return patentType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PATENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPatentType() {
    return patentType;
  }


  @JsonProperty(JSON_PROPERTY_PATENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPatentType(@javax.annotation.Nullable String patentType) {
    this.patentType = patentType;
  }

  public UsptoPatent url(@javax.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * URL of the original article.
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUrl() {
    return url;
  }


  @JsonProperty(JSON_PROPERTY_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UsptoPatent usptoPatent = (UsptoPatent) o;
    return Objects.equals(this.applicationNumber, usptoPatent.applicationNumber) &&
        Objects.equals(this.companyFilingName, usptoPatent.companyFilingName) &&
        Objects.equals(this.filingDate, usptoPatent.filingDate) &&
        Objects.equals(this.description, usptoPatent.description) &&
        Objects.equals(this.filingStatus, usptoPatent.filingStatus) &&
        Objects.equals(this.patentNumber, usptoPatent.patentNumber) &&
        Objects.equals(this.publicationDate, usptoPatent.publicationDate) &&
        Objects.equals(this.patentType, usptoPatent.patentType) &&
        Objects.equals(this.url, usptoPatent.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationNumber, companyFilingName, filingDate, description, filingStatus, patentNumber, publicationDate, patentType, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UsptoPatent {\n");
    sb.append("    applicationNumber: ").append(toIndentedString(applicationNumber)).append("\n");
    sb.append("    companyFilingName: ").append(toIndentedString(companyFilingName)).append("\n");
    sb.append("    filingDate: ").append(toIndentedString(filingDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    filingStatus: ").append(toIndentedString(filingStatus)).append("\n");
    sb.append("    patentNumber: ").append(toIndentedString(patentNumber)).append("\n");
    sb.append("    publicationDate: ").append(toIndentedString(publicationDate)).append("\n");
    sb.append("    patentType: ").append(toIndentedString(patentType)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

