/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BondYieldCurveInfo
 */
class BondYieldCurveInfoTest {
    private final BondYieldCurveInfo model = new BondYieldCurveInfo();

    /**
     * Model tests for BondYieldCurveInfo
     */
    @Test
    void testBondYieldCurveInfo() {
        // TODO: test BondYieldCurveInfo
    }

    /**
     * Test the property 'd'
     */
    @Test
    void dTest() {
        // TODO: test d
    }

    /**
     * Test the property 'v'
     */
    @Test
    void vTest() {
        // TODO: test v
    }

}
