/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BondTickData
 */
class BondTickDataTest {
    private final BondTickData model = new BondTickData();

    /**
     * Model tests for BondTickData
     */
    @Test
    void testBondTickData() {
        // TODO: test BondTickData
    }

    /**
     * Test the property 'skip'
     */
    @Test
    void skipTest() {
        // TODO: test skip
    }

    /**
     * Test the property 'count'
     */
    @Test
    void countTest() {
        // TODO: test count
    }

    /**
     * Test the property 'total'
     */
    @Test
    void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'v'
     */
    @Test
    void vTest() {
        // TODO: test v
    }

    /**
     * Test the property 'p'
     */
    @Test
    void pTest() {
        // TODO: test p
    }

    /**
     * Test the property 'y'
     */
    @Test
    void yTest() {
        // TODO: test y
    }

    /**
     * Test the property 't'
     */
    @Test
    void tTest() {
        // TODO: test t
    }

    /**
     * Test the property 'si'
     */
    @Test
    void siTest() {
        // TODO: test si
    }

    /**
     * Test the property 'cp'
     */
    @Test
    void cpTest() {
        // TODO: test cp
    }

    /**
     * Test the property 'rp'
     */
    @Test
    void rpTest() {
        // TODO: test rp
    }

    /**
     * Test the property 'ats'
     */
    @Test
    void atsTest() {
        // TODO: test ats
    }

    /**
     * Test the property 'c'
     */
    @Test
    void cTest() {
        // TODO: test c
    }

}
