/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CovidInfo
 */
class CovidInfoTest {
    private final CovidInfo model = new CovidInfo();

    /**
     * Model tests for CovidInfo
     */
    @Test
    void testCovidInfo() {
        // TODO: test CovidInfo
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property '_case'
     */
    @Test
    void _caseTest() {
        // TODO: test _case
    }

    /**
     * Test the property 'death'
     */
    @Test
    void deathTest() {
        // TODO: test death
    }

    /**
     * Test the property 'updated'
     */
    @Test
    void updatedTest() {
        // TODO: test updated
    }

}
