/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dividends
 */
class DividendsTest {
    private final Dividends model = new Dividends();

    /**
     * Model tests for Dividends
     */
    @Test
    void testDividends() {
        // TODO: test Dividends
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'date'
     */
    @Test
    void dateTest() {
        // TODO: test date
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'adjustedAmount'
     */
    @Test
    void adjustedAmountTest() {
        // TODO: test adjustedAmount
    }

    /**
     * Test the property 'payDate'
     */
    @Test
    void payDateTest() {
        // TODO: test payDate
    }

    /**
     * Test the property 'recordDate'
     */
    @Test
    void recordDateTest() {
        // TODO: test recordDate
    }

    /**
     * Test the property 'declarationDate'
     */
    @Test
    void declarationDateTest() {
        // TODO: test declarationDate
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'freq'
     */
    @Test
    void freqTest() {
        // TODO: test freq
    }

}
