/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EarningsEstimatesInfo
 */
class EarningsEstimatesInfoTest {
    private final EarningsEstimatesInfo model = new EarningsEstimatesInfo();

    /**
     * Model tests for EarningsEstimatesInfo
     */
    @Test
    void testEarningsEstimatesInfo() {
        // TODO: test EarningsEstimatesInfo
    }

    /**
     * Test the property 'epsAvg'
     */
    @Test
    void epsAvgTest() {
        // TODO: test epsAvg
    }

    /**
     * Test the property 'epsHigh'
     */
    @Test
    void epsHighTest() {
        // TODO: test epsHigh
    }

    /**
     * Test the property 'epsLow'
     */
    @Test
    void epsLowTest() {
        // TODO: test epsLow
    }

    /**
     * Test the property 'numberAnalysts'
     */
    @Test
    void numberAnalystsTest() {
        // TODO: test numberAnalysts
    }

    /**
     * Test the property 'period'
     */
    @Test
    void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'year'
     */
    @Test
    void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'quarter'
     */
    @Test
    void quarterTest() {
        // TODO: test quarter
    }

}
