/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for EbitdaEstimatesInfo
 */
class EbitdaEstimatesInfoTest {
    private final EbitdaEstimatesInfo model = new EbitdaEstimatesInfo();

    /**
     * Model tests for EbitdaEstimatesInfo
     */
    @Test
    void testEbitdaEstimatesInfo() {
        // TODO: test EbitdaEstimatesInfo
    }

    /**
     * Test the property 'ebitdaAvg'
     */
    @Test
    void ebitdaAvgTest() {
        // TODO: test ebitdaAvg
    }

    /**
     * Test the property 'ebitdaHigh'
     */
    @Test
    void ebitdaHighTest() {
        // TODO: test ebitdaHigh
    }

    /**
     * Test the property 'ebitdaLow'
     */
    @Test
    void ebitdaLowTest() {
        // TODO: test ebitdaLow
    }

    /**
     * Test the property 'numberAnalysts'
     */
    @Test
    void numberAnalystsTest() {
        // TODO: test numberAnalysts
    }

    /**
     * Test the property 'period'
     */
    @Test
    void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'year'
     */
    @Test
    void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'quarter'
     */
    @Test
    void quarterTest() {
        // TODO: test quarter
    }

}
