/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InternationalFiling
 */
class InternationalFilingTest {
    private final InternationalFiling model = new InternationalFiling();

    /**
     * Model tests for InternationalFiling
     */
    @Test
    void testInternationalFiling() {
        // TODO: test InternationalFiling
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'filedDate'
     */
    @Test
    void filedDateTest() {
        // TODO: test filedDate
    }

    /**
     * Test the property 'category'
     */
    @Test
    void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'language'
     */
    @Test
    void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

}
