/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MarketHolidayData
 */
class MarketHolidayDataTest {
    private final MarketHolidayData model = new MarketHolidayData();

    /**
     * Model tests for MarketHolidayData
     */
    @Test
    void testMarketHolidayData() {
        // TODO: test MarketHolidayData
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'atDate'
     */
    @Test
    void atDateTest() {
        // TODO: test atDate
    }

    /**
     * Test the property 'tradingHour'
     */
    @Test
    void tradingHourTest() {
        // TODO: test tradingHour
    }

}
