/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.MutualFundCountryExposureData;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MutualFundCountryExposure
 */
class MutualFundCountryExposureTest {
    private final MutualFundCountryExposure model = new MutualFundCountryExposure();

    /**
     * Model tests for MutualFundCountryExposure
     */
    @Test
    void testMutualFundCountryExposure() {
        // TODO: test MutualFundCountryExposure
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'countryExposure'
     */
    @Test
    void countryExposureTest() {
        // TODO: test countryExposure
    }

}
