/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VisaApplication
 */
class VisaApplicationTest {
    private final VisaApplication model = new VisaApplication();

    /**
     * Model tests for VisaApplication
     */
    @Test
    void testVisaApplication() {
        // TODO: test VisaApplication
    }

    /**
     * Test the property 'year'
     */
    @Test
    void yearTest() {
        // TODO: test year
    }

    /**
     * Test the property 'quarter'
     */
    @Test
    void quarterTest() {
        // TODO: test quarter
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'caseNumber'
     */
    @Test
    void caseNumberTest() {
        // TODO: test caseNumber
    }

    /**
     * Test the property 'caseStatus'
     */
    @Test
    void caseStatusTest() {
        // TODO: test caseStatus
    }

    /**
     * Test the property 'receivedDate'
     */
    @Test
    void receivedDateTest() {
        // TODO: test receivedDate
    }

    /**
     * Test the property 'visaClass'
     */
    @Test
    void visaClassTest() {
        // TODO: test visaClass
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'socCode'
     */
    @Test
    void socCodeTest() {
        // TODO: test socCode
    }

    /**
     * Test the property 'fullTimePosition'
     */
    @Test
    void fullTimePositionTest() {
        // TODO: test fullTimePosition
    }

    /**
     * Test the property 'beginDate'
     */
    @Test
    void beginDateTest() {
        // TODO: test beginDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'employerName'
     */
    @Test
    void employerNameTest() {
        // TODO: test employerName
    }

    /**
     * Test the property 'worksiteAddress'
     */
    @Test
    void worksiteAddressTest() {
        // TODO: test worksiteAddress
    }

    /**
     * Test the property 'worksiteCity'
     */
    @Test
    void worksiteCityTest() {
        // TODO: test worksiteCity
    }

    /**
     * Test the property 'worksiteCounty'
     */
    @Test
    void worksiteCountyTest() {
        // TODO: test worksiteCounty
    }

    /**
     * Test the property 'worksiteState'
     */
    @Test
    void worksiteStateTest() {
        // TODO: test worksiteState
    }

    /**
     * Test the property 'worksitePostalCode'
     */
    @Test
    void worksitePostalCodeTest() {
        // TODO: test worksitePostalCode
    }

    /**
     * Test the property 'wageRangeFrom'
     */
    @Test
    void wageRangeFromTest() {
        // TODO: test wageRangeFrom
    }

    /**
     * Test the property 'wageRangeTo'
     */
    @Test
    void wageRangeToTest() {
        // TODO: test wageRangeTo
    }

    /**
     * Test the property 'wageUnitOfPay'
     */
    @Test
    void wageUnitOfPayTest() {
        // TODO: test wageUnitOfPay
    }

    /**
     * Test the property 'wageLevel'
     */
    @Test
    void wageLevelTest() {
        // TODO: test wageLevel
    }

    /**
     * Test the property 'h1bDependent'
     */
    @Test
    void h1bDependentTest() {
        // TODO: test h1bDependent
    }

}
