/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ETFSectorExposureData
 */
class ETFSectorExposureDataTest {
    private final ETFSectorExposureData model = new ETFSectorExposureData();

    /**
     * Model tests for ETFSectorExposureData
     */
    @Test
    void testETFSectorExposureData() {
        // TODO: test ETFSectorExposureData
    }

    /**
     * Test the property 'industry'
     */
    @Test
    void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'exposure'
     */
    @Test
    void exposureTest() {
        // TODO: test exposure
    }

}
