/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for IsinChangeInfo
 */
class IsinChangeInfoTest {
    private final IsinChangeInfo model = new IsinChangeInfo();

    /**
     * Model tests for IsinChangeInfo
     */
    @Test
    void testIsinChangeInfo() {
        // TODO: test IsinChangeInfo
    }

    /**
     * Test the property 'atDate'
     */
    @Test
    void atDateTest() {
        // TODO: test atDate
    }

    /**
     * Test the property 'oldIsin'
     */
    @Test
    void oldIsinTest() {
        // TODO: test oldIsin
    }

    /**
     * Test the property 'newIsin'
     */
    @Test
    void newIsinTest() {
        // TODO: test newIsin
    }

}
