/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SentimentContent
 */
class SentimentContentTest {
    private final SentimentContent model = new SentimentContent();

    /**
     * Model tests for SentimentContent
     */
    @Test
    void testSentimentContent() {
        // TODO: test SentimentContent
    }

    /**
     * Test the property 'mention'
     */
    @Test
    void mentionTest() {
        // TODO: test mention
    }

    /**
     * Test the property 'positiveMention'
     */
    @Test
    void positiveMentionTest() {
        // TODO: test positiveMention
    }

    /**
     * Test the property 'negativeMention'
     */
    @Test
    void negativeMentionTest() {
        // TODO: test negativeMention
    }

    /**
     * Test the property 'positiveScore'
     */
    @Test
    void positiveScoreTest() {
        // TODO: test positiveScore
    }

    /**
     * Test the property 'negativeScore'
     */
    @Test
    void negativeScoreTest() {
        // TODO: test negativeScore
    }

    /**
     * Test the property 'score'
     */
    @Test
    void scoreTest() {
        // TODO: test score
    }

    /**
     * Test the property 'atTime'
     */
    @Test
    void atTimeTest() {
        // TODO: test atTime
    }

}
