/*
 * Finnhub API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package bbb.finnhub.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FDAComitteeMeeting
 */
class FDAComitteeMeetingTest {
    private final FDAComitteeMeeting model = new FDAComitteeMeeting();

    /**
     * Model tests for FDAComitteeMeeting
     */
    @Test
    void testFDAComitteeMeeting() {
        // TODO: test FDAComitteeMeeting
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    void toDateTest() {
        // TODO: test toDate
    }

    /**
     * Test the property 'eventDescription'
     */
    @Test
    void eventDescriptionTest() {
        // TODO: test eventDescription
    }

    /**
     * Test the property 'url'
     */
    @Test
    void urlTest() {
        // TODO: test url
    }

}
